#!/usr/bin/env python
"""
BRレコードパーサー: １６．生産者マスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from src.jvlink.constants import ENCODING_JVDATA
from src.utils.logger import get_logger


class BRParser:
    """
    BRレコードパーサー

    １６．生産者マスタ
    レコード長: 545 bytes
    VBテーブル名: SEISAN
    """

    RECORD_TYPE = "BR"
    RECORD_LENGTH = 545

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """Strictly decode one byte-sliced CP932 field and trim padding."""
        return data.decode(ENCODING_JVDATA).strip()

    def parse(self, data: bytes) -> dict[str, str] | None:
        """
        BRレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            if len(data) != self.RECORD_LENGTH:
                self.logger.warning(f"BRレコード長不正: expected={self.RECORD_LENGTH}, actual={len(data)}")
                return None
            if data[:2] != self.RECORD_TYPE.encode("ascii"):
                self.logger.warning("BRレコード種別不正")
                return None
            if data[543:545] != b"\r\n":
                self.logger.warning("BRレコード区切り不正")
                return None

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 生産者コード (位置:12, 長さ:8)
            result["BreederCode"] = self.decode_field(data[11:19])

            # 5. 生産者名(法人格有) (位置:20, 長さ:72)
            result["BreederName_Co"] = self.decode_field(data[19:91])

            # 6. 生産者名(法人格無) (位置:92, 長さ:72)
            result["BreederName"] = self.decode_field(data[91:163])

            # 7. 生産者名半角ｶﾅ (位置:164, 長さ:72)
            result["BreederNameKana"] = self.decode_field(data[163:235])

            # 8. 生産者名欧字 (位置:236, 長さ:168)
            result["BreederNameEng"] = self.decode_field(data[235:403])

            # 9. 生産者住所自治省名 (位置:404, 長さ:20)
            result["Address"] = self.decode_field(data[403:423])

            # 10. <本年･累計成績情報> (位置:424, 2回, 60 bytes)
            result["H_SetYear"] = self.decode_field(data[423:427])
            result["H_HonSyokinTotal"] = self.decode_field(data[427:437])
            result["H_FukaSyokin"] = self.decode_field(data[437:447])
            result["H_ChakuKaisu1"] = self.decode_field(data[447:453])
            result["H_ChakuKaisu2"] = self.decode_field(data[453:459])
            result["H_ChakuKaisu3"] = self.decode_field(data[459:465])
            result["H_ChakuKaisu4"] = self.decode_field(data[465:471])
            result["H_ChakuKaisu5"] = self.decode_field(data[471:477])
            result["H_ChakuKaisu6"] = self.decode_field(data[477:483])

            result["R_SetYear"] = self.decode_field(data[483:487])
            result["R_HonSyokinTotal"] = self.decode_field(data[487:497])
            result["R_FukaSyokin"] = self.decode_field(data[497:507])
            result["R_ChakuKaisu1"] = self.decode_field(data[507:513])
            result["R_ChakuKaisu2"] = self.decode_field(data[513:519])
            result["R_ChakuKaisu3"] = self.decode_field(data[519:525])
            result["R_ChakuKaisu4"] = self.decode_field(data[525:531])
            result["R_ChakuKaisu5"] = self.decode_field(data[531:537])
            result["R_ChakuKaisu6"] = self.decode_field(data[537:543])

            # 11. レコード区切 (位置:544, 長さ:2)
            result["RecordDelimiter"] = self.decode_field(data[543:545])

            return result

        except Exception as e:
            self.logger.error(f"BRレコードパース中にエラー: {e}")
            return None
