#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
CSレコードパーサー: ２７．コース情報

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from datetime import datetime
from typing import Any, Dict, List

from src.parser.base import BaseParser, FieldDef


class CSParser(BaseParser):
    """
    CSレコードパーサー

    ２７．コース情報
    レコード長: 6829 bytes
    VBテーブル名: COURSE
    """

    record_type = "CS"
    RECORD_LENGTH = 6829
    TRACK_CD_VALUES = frozenset(
        {"00"}
        | {str(value) for value in range(10, 30)}
        | {str(value) for value in range(51, 60)}
    )

    @staticmethod
    def _require_ascii_digits(field_name: str, value: Any, width: int) -> None:
        if (
            not isinstance(value, str)
            or len(value) != width
            or not value.isascii()
            or not value.isdigit()
        ):
            raise ValueError(
                f"CS {field_name} must be exactly {width} ASCII digits"
            )

    @classmethod
    def _require_yyyymmdd(cls, field_name: str, value: Any) -> None:
        cls._require_ascii_digits(field_name, value, 8)
        try:
            datetime.strptime(value, "%Y%m%d")
        except ValueError as error:
            raise ValueError(f"CS {field_name} must be a real YYYYMMDD date") from error

    @classmethod
    def validate_key_fields(cls, record: Dict[str, Any]) -> None:
        """Validate the current header and official four-part CS identity."""

        cls._require_yyyymmdd("MakeDate", record.get("MakeDate"))
        jyo_cd = record.get("JyoCD")
        if (
            not isinstance(jyo_cd, str)
            or len(jyo_cd) != 2
            or not jyo_cd.isascii()
            or not jyo_cd.isalnum()
        ):
            raise ValueError("CS JyoCD must be a 2-character ASCII code")
        cls._require_ascii_digits("Kyori", record.get("Kyori"), 4)
        track_cd = record.get("TrackCD")
        if track_cd not in cls.TRACK_CD_VALUES:
            raise ValueError(f"CS TrackCD is not in official code table 2009: {track_cd!r}")
        cls._require_yyyymmdd("KaishuDate", record.get("KaishuDate"))

    def parse(self, record: bytes) -> Dict[str, Any]:
        """Parse one exact current CS record and reject malformed identities."""

        parsed = super().parse(record)
        self.validate_key_fields(parsed)
        return parsed

    def _define_fields(self) -> List[FieldDef]:
        """Define field positions for CS record.

        Returns:
            List of FieldDef objects
        """
        return [
            FieldDef("RecordSpec", 0, 2),        # レコード種別ID
            FieldDef("DataKubun", 2, 1),         # データ区分
            FieldDef("MakeDate", 3, 8),          # データ作成年月日
            FieldDef("JyoCD", 11, 2),            # 競馬場コード
            FieldDef("Kyori", 13, 4),            # 距離
            FieldDef("TrackCD", 17, 2),          # トラックコード
            FieldDef("KaishuDate", 19, 8),       # コース改修年月日
            FieldDef("CourseEx", 27, 6800),      # コース説明
            FieldDef("RecordDelimiter", 6827, 2),      # レコード区切
        ]
