#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
CSレコードパーサー: ２７．コース情報

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from datetime import datetime
from typing import Any, Dict, List

from src.parser.base import BaseParser, FieldDef
from src.parser.code_domains import (
    OFFICIAL_JYO_CODES_2001,
    OFFICIAL_TRACK_CODES_2009,
)


class CSParser(BaseParser):
    """
    CSレコードパーサー

    ２７．コース情報
    レコード長: 6829 bytes
    VBテーブル名: COURSE
    """

    record_type = "CS"
    RECORD_LENGTH = 6829
    COURSE_EX_BYTES = 6800
    OFFICIAL_JYO_CODES = OFFICIAL_JYO_CODES_2001
    TRACK_CD_VALUES = OFFICIAL_TRACK_CODES_2009

    @staticmethod
    def _require_ascii_digits(field_name: str, value: Any, width: int) -> None:
        if (
            not isinstance(value, str)
            or len(value) != width
            or not value.isascii()
            or not value.isdigit()
        ):
            raise ValueError(
                f"CS {field_name} must be exactly {width} ASCII digits"
            )

    @classmethod
    def _require_yyyymmdd(cls, field_name: str, value: Any) -> None:
        cls._require_ascii_digits(field_name, value, 8)
        try:
            datetime.strptime(value, "%Y%m%d")
        except ValueError as error:
            raise ValueError(f"CS {field_name} must be a real YYYYMMDD date") from error

    @classmethod
    def validate_key_fields(cls, record: Dict[str, Any]) -> None:
        """Validate the current header and official four-part CS identity."""

        cls._require_yyyymmdd("MakeDate", record.get("MakeDate"))
        jyo_cd = record.get("JyoCD")
        if jyo_cd not in cls.OFFICIAL_JYO_CODES:
            raise ValueError("CS JyoCD is not in official code table 2001")
        cls._require_ascii_digits("Kyori", record.get("Kyori"), 4)
        track_cd = record.get("TrackCD")
        if track_cd not in cls.TRACK_CD_VALUES:
            raise ValueError(f"CS TrackCD is not in official code table 2009: {track_cd!r}")
        cls._require_yyyymmdd("KaishuDate", record.get("KaishuDate"))

    @classmethod
    def validate_body_field(cls, record: Dict[str, Any]) -> None:
        """Require a caller body that could occupy the official physical field."""

        course_ex = record.get("CourseEx")
        if not isinstance(course_ex, str):
            raise ValueError("CS CourseEx must be a string")
        try:
            encoded = course_ex.encode("cp932", errors="strict")
        except UnicodeEncodeError as error:
            raise ValueError("CS CourseEx must be strict CP932 text") from error
        if len(encoded) > cls.COURSE_EX_BYTES:
            raise ValueError(
                f"CS CourseEx must be at most {cls.COURSE_EX_BYTES} CP932 bytes"
            )

    @classmethod
    def validate_current_fields(
        cls, record: Dict[str, Any], *, data_kubun: str | None = None
    ) -> None:
        """Validate one current CS record before returning or mutating storage."""

        cls.validate_key_fields(record)
        status = data_kubun if data_kubun is not None else record.get("DataKubun")
        if status != "0":
            cls.validate_body_field(record)

    def parse(self, record: bytes) -> Dict[str, Any]:
        """Parse one exact current CS record and reject malformed identities."""

        parsed = super().parse(record)
        self.validate_current_fields(parsed)
        return parsed

    def _define_fields(self) -> List[FieldDef]:
        """Define field positions for CS record.

        Returns:
            List of FieldDef objects
        """
        return [
            FieldDef("RecordSpec", 0, 2),        # レコード種別ID
            FieldDef("DataKubun", 2, 1),         # データ区分
            FieldDef("MakeDate", 3, 8),          # データ作成年月日
            FieldDef("JyoCD", 11, 2),            # 競馬場コード
            FieldDef("Kyori", 13, 4),            # 距離
            FieldDef("TrackCD", 17, 2),          # トラックコード
            FieldDef("KaishuDate", 19, 8),       # コース改修年月日
            FieldDef("CourseEx", 27, 6800),      # コース説明
            FieldDef("RecordDelimiter", 6827, 2),      # レコード区切
        ]
