#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
DMレコードパーサー: ２８．タイム型データマイニング予想

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class DMParser:
    """
    DMレコードパーサー

    ２８．タイム型データマイニング予想
    レコード長: 48 bytes
    VBテーブル名: MINING
    """

    RECORD_TYPE = "DM"
    RECORD_LENGTH = 48

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        DMレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"DMレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Year"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["MonthDay"] = self.decode_field(data[15:19])

            # 6. 競馬場コード (位置:20, 長さ:2)
            result["JyoCD"] = self.decode_field(data[19:21])

            # 7. 開催回[第N回] (位置:22, 長さ:2)
            result["Kaiji"] = self.decode_field(data[21:23])

            # 8. 開催日目[N日目] (位置:24, 長さ:2)
            result["Nichiji"] = self.decode_field(data[23:25])

            # 9. レース番号 (位置:26, 長さ:2)
            result["RaceNum"] = self.decode_field(data[25:27])

            # 10. データ作成時分 (位置:28, 長さ:4)
            result["MakeHM"] = self.decode_field(data[27:31])

            # 11. <マイニング予想> (位置:32, 長さ:0)
            result["Umaban1"] = self.decode_field(data[31:31])

            # 12. 馬番 (位置:32, 長さ:2)
            result["DMTime1"] = self.decode_field(data[31:33])

            # 13. 予想走破タイム (位置:34, 長さ:5)
            result["DMGosaP1"] = self.decode_field(data[33:38])

            # 14. 予想誤差(信頼度)＋ (位置:39, 長さ:4)
            result["DMGosaM1"] = self.decode_field(data[38:42])

            # 15. 予想誤差(信頼度)－ (位置:43, 長さ:4)
            result["Umaban2"] = self.decode_field(data[42:46])

            # 16. レコード区切 (位置:47, 長さ:2)
            result["DMTime2"] = self.decode_field(data[46:48])

            return result

        except Exception as e:
            self.logger.error(f"DMレコードパース中にエラー: {e}")
            return None
