#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
H1レコードパーサー: ５．票数１

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class H1Parser:
    """
    H1レコードパーサー

    ５．票数１
    レコード長: 317 bytes
    VBテーブル名: HYOSU
    """

    RECORD_TYPE = "H1"
    RECORD_LENGTH = 317

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        H1レコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"H1レコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Year"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["MonthDay"] = self.decode_field(data[15:19])

            # 6. 競馬場コード (位置:20, 長さ:2)
            result["JyoCD"] = self.decode_field(data[19:21])

            # 7. 開催回[第N回] (位置:22, 長さ:2)
            result["Kaiji"] = self.decode_field(data[21:23])

            # 8. 開催日目[N日目] (位置:24, 長さ:2)
            result["Nichiji"] = self.decode_field(data[23:25])

            # 9. レース番号 (位置:26, 長さ:2)
            result["RaceNum"] = self.decode_field(data[25:27])

            # 10. 登録頭数 (位置:28, 長さ:2)
            result["TorokuTosu"] = self.decode_field(data[27:29])

            # 11. 出走頭数 (位置:30, 長さ:2)
            result["SyussoTosu"] = self.decode_field(data[29:31])

            # 12. 発売フラグ　単勝 (位置:32, 長さ:1)
            result["HatubaiFlag1"] = self.decode_field(data[31:32])

            # 13. 発売フラグ　複勝 (位置:33, 長さ:1)
            result["HatubaiFlag2"] = self.decode_field(data[32:33])

            # 14. 発売フラグ　枠連 (位置:34, 長さ:1)
            result["HatubaiFlag3"] = self.decode_field(data[33:34])

            # 15. 発売フラグ　馬連 (位置:35, 長さ:1)
            result["HatubaiFlag4"] = self.decode_field(data[34:35])

            # 16. 発売フラグ　ワイド (位置:36, 長さ:1)
            result["HatubaiFlag5"] = self.decode_field(data[35:36])

            # 17. 発売フラグ　馬単 (位置:37, 長さ:1)
            result["HatubaiFlag6"] = self.decode_field(data[36:37])

            # 18. 発売フラグ　3連複 (位置:38, 長さ:1)
            result["HatubaiFlag7"] = self.decode_field(data[37:38])

            # 19. 複勝着払キー (位置:39, 長さ:1)
            result["FukuChakuBaraiKey"] = self.decode_field(data[38:39])

            # 20. 返還馬番情報(馬番01～28) (位置:40, 長さ:1)
            result["HenkanUma1"] = self.decode_field(data[39:40])

            # 21. 返還枠番情報(枠番1～8) (位置:41, 長さ:1)
            result["HenkanUma2"] = self.decode_field(data[40:41])

            # 22. 返還同枠情報(枠番1～8) (位置:42, 長さ:1)
            result["HenkanUma3"] = self.decode_field(data[41:42])

            # 23. <単勝票数> (位置:43, 長さ:0)
            # (This is a section header, no data)

            # 24. 　　馬番 (位置:43, 長さ:2)
            result["TanUma"] = self.decode_field(data[42:44])

            # 25. 　　票数 (位置:45, 長さ:11)
            result["TanHyo"] = self.decode_field(data[44:55])

            # 26. 　　人気順 (位置:56, 長さ:2)
            result["TanNinki"] = self.decode_field(data[55:57])

            # 27. <複勝票数> (位置:58, 長さ:0)
            # (This is a section header, no data)

            # 28. 　　馬番 (位置:58, 長さ:2)
            result["FukuUma"] = self.decode_field(data[57:59])

            # 29. 　　票数 (位置:60, 長さ:11)
            result["FukuHyo"] = self.decode_field(data[59:70])

            # 30. 　　人気順 (位置:71, 長さ:2)
            result["FukuNinki"] = self.decode_field(data[70:72])

            # 31. <枠連票数> (位置:73, 長さ:0)
            # (This is a section header, no data)

            # 32. 　　組番 (位置:73, 長さ:2)
            result["WakuKumi"] = self.decode_field(data[72:74])

            # 33. 　　票数 (位置:75, 長さ:11)
            result["WakuHyo"] = self.decode_field(data[74:85])

            # 34. 　　人気順 (位置:86, 長さ:2)
            result["WakuNinki"] = self.decode_field(data[85:87])

            # 35. <馬連票数> (位置:88, 長さ:0)
            # (This is a section header, no data)

            # 36. 　　組番 (位置:88, 長さ:4)
            result["UmarenKumi"] = self.decode_field(data[87:91])

            # 37. 　　票数 (位置:92, 長さ:11)
            result["UmarenHyo"] = self.decode_field(data[91:102])

            # 38. 　　人気順 (位置:103, 長さ:3)
            result["UmarenNinki"] = self.decode_field(data[102:105])

            # 39. <ワイド票数> (位置:106, 長さ:0)
            # (This is a section header, no data)

            # 40. 　　組番 (位置:106, 長さ:4)
            result["WideKumi"] = self.decode_field(data[105:109])

            # 41. 　　票数 (位置:110, 長さ:11)
            result["WideHyo"] = self.decode_field(data[109:120])

            # 42. 　　人気順 (位置:121, 長さ:3)
            result["WideNinki"] = self.decode_field(data[120:123])

            # 43. <馬単票数> (位置:124, 長さ:0)
            # (This is a section header, no data)

            # 44. 　　組番 (位置:124, 長さ:4)
            result["UmatanKumi"] = self.decode_field(data[123:127])

            # 45. 　　票数 (位置:128, 長さ:11)
            result["UmatanHyo"] = self.decode_field(data[127:138])

            # 46. 　　人気順 (位置:139, 長さ:3)
            result["UmatanNinki"] = self.decode_field(data[138:141])

            # 47. <3連複票数> (位置:142, 長さ:0)
            # (This is a section header, no data)

            # 48. 　　組番 (位置:142, 長さ:6)
            result["SanrenfukuKumi"] = self.decode_field(data[141:147])

            # 49. 　　票数 (位置:148, 長さ:11)
            result["SanrenfukuHyo"] = self.decode_field(data[147:158])

            # 50. 　　人気順 (位置:159, 長さ:3)
            result["SanrenfukuNinki"] = self.decode_field(data[158:161])

            # 51. 単勝票数合計 (位置:162, 長さ:11)
            result["TanHyoTotal"] = self.decode_field(data[161:172])

            # 52. 複勝票数合計 (位置:173, 長さ:11)
            result["FukuHyoTotal"] = self.decode_field(data[172:183])

            # 53. 枠連票数合計 (位置:184, 長さ:11)
            result["WakuHyoTotal"] = self.decode_field(data[183:194])

            # 54. 馬連票数合計 (位置:195, 長さ:11)
            result["UmarenHyoTotal"] = self.decode_field(data[194:205])

            # 55. ワイド票数合計 (位置:206, 長さ:11)
            result["WideHyoTotal"] = self.decode_field(data[205:216])

            # 56. 馬単票数合計 (位置:217, 長さ:11)
            result["UmatanHyoTotal"] = self.decode_field(data[216:227])

            # 57. 3連複票数合計 (位置:228, 長さ:11)
            result["SanrenfukuHyoTotal"] = self.decode_field(data[227:238])

            # 58. 単勝返還票数合計 (位置:239, 長さ:11)
            result["TanHenkanHyoTotal"] = self.decode_field(data[238:249])

            # 59. 複勝返還票数合計 (位置:250, 長さ:11)
            result["FukuHenkanHyoTotal"] = self.decode_field(data[249:260])

            # 60. 枠連返還票数合計 (位置:261, 長さ:11)
            result["WakuHenkanHyoTotal"] = self.decode_field(data[260:271])

            # 61. 馬連返還票数合計 (位置:272, 長さ:11)
            result["UmarenHenkanHyoTotal"] = self.decode_field(data[271:282])

            # 62. ワイド返還票数合計 (位置:283, 長さ:11)
            result["WideHenkanHyoTotal"] = self.decode_field(data[282:293])

            # 63. 馬単返還票数合計 (位置:294, 長さ:11)
            result["UmatanHenkanHyoTotal"] = self.decode_field(data[293:304])

            # 64. 3連複返還票数合計 (位置:305, 長さ:11)
            result["SanrenfukuHenkanHyoTotal"] = self.decode_field(data[304:315])

            # 65. レコード区切 (位置:316, 長さ:2)
            result["RecordDelimiter"] = self.decode_field(data[315:317])

            return result

        except Exception as e:
            self.logger.error(f"H1レコードパース中にエラー: {e}")
            return None
