#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
HCレコードパーサー: ２２．坂路調教

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class HCParser:
    """
    HCレコードパーサー

    ２２．坂路調教
    レコード長: 60 bytes
    VBテーブル名: CHOKYO_SEISEKI
    """

    RECORD_TYPE = "HC"
    RECORD_LENGTH = 60

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        HCレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"HCレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["ChokyosiCode"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["Num"] = self.decode_field(data[3:11])

            # 4. トレセン区分 (位置:12, 長さ:1)
            result["SetYear"] = self.decode_field(data[11:12])

            # 5. 調教年月日 (位置:13, 長さ:8)
            result["HonSyokinHeichi"] = self.decode_field(data[12:20])

            # 6. 調教時刻 (位置:21, 長さ:4)
            result["HonSyokinSyogai"] = self.decode_field(data[20:24])

            # 7. 血統登録番号 (位置:25, 長さ:10)
            result["FukaSyokinHeichi"] = self.decode_field(data[24:34])

            # 8. <4ハロン800M> (位置:35, 長さ:0)
            result["FukaSyokinSyogai"] = self.decode_field(data[34:34])

            # 9. 4ハロンタイム合計(800M～0M) (位置:35, 長さ:4)
            result["HeichiChakukaisu1"] = self.decode_field(data[34:38])

            # 10. ラップタイム(800M～600M) (位置:39, 長さ:3)
            result["HeichiChakukaisu2"] = self.decode_field(data[38:41])

            # 11. <3ハロン600M> (位置:42, 長さ:0)
            result["HeichiChakukaisu3"] = self.decode_field(data[41:41])

            # 12. 3ハロンタイム合計(600M～0M) (位置:42, 長さ:4)
            result["HeichiChakukaisu4"] = self.decode_field(data[41:45])

            # 13. ラップタイム(600M～400M) (位置:46, 長さ:3)
            result["HeichiChakukaisu5"] = self.decode_field(data[45:48])

            # 14. <2ハロン400M> (位置:49, 長さ:0)
            result["HeichiChakukaisu6"] = self.decode_field(data[48:48])

            # 15. 2ハロンタイム合計(400M～0M) (位置:49, 長さ:4)
            result["SyogaiChakukaisu1"] = self.decode_field(data[48:52])

            # 16. ラップタイム(400M～200M) (位置:53, 長さ:3)
            result["SyogaiChakukaisu2"] = self.decode_field(data[52:55])

            # 17. <1ハロン200M> (位置:56, 長さ:0)
            result["SyogaiChakukaisu3"] = self.decode_field(data[55:55])

            # 18. ラップタイム(200M～0M) (位置:56, 長さ:3)
            result["SyogaiChakukaisu4"] = self.decode_field(data[55:58])

            # 19. レコード区切 (位置:59, 長さ:2)
            result["SyogaiChakukaisu5"] = self.decode_field(data[58:60])

            return result

        except Exception as e:
            self.logger.error(f"HCレコードパース中にエラー: {e}")
            return None
