#!/usr/bin/env python
"""
HNレコードパーサー: １８．繁殖馬マスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from collections.abc import Mapping
from datetime import date

from src.parser import status_domain
from src.utils.logger import get_logger


class HNParser:
    """
    HNレコードパーサー

    １８．繁殖馬マスタ
    レコード長: 251 bytes
    VBテーブル名: HANSYOKU
    """

    RECORD_TYPE = "HN"
    RECORD_LENGTH = 251
    RECORD_DELIMITER_START = 249
    KEY_COLUMNS = ("HansyokuNum",)
    MOCHI_KUBUN_VALUES = frozenset({"0", "1", "2", "3", "9"})
    TEXT_FIELD_WIDTHS = {
        "Bamei": 36,
        "BameiKana": 40,
        "BameiEng": 80,
        "SanchiName": 20,
    }

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        return data.decode("cp932", errors="strict").strip()

    @staticmethod
    def _require_ascii_digits(field_name: str, value: object, width: int) -> str:
        if isinstance(value, str) and len(value) == width and value.isascii() and value.isdigit():
            return value
        raise ValueError(f"HN {field_name} must be exactly {width} ASCII digits")

    @classmethod
    def _require_date(cls, field_name: str, value: object) -> str:
        digits = cls._require_ascii_digits(field_name, value, 8)
        try:
            date(int(digits[:4]), int(digits[4:6]), int(digits[6:]))
        except ValueError as error:
            raise ValueError(f"HN {field_name} must be a real YYYYMMDD date") from error
        return digits

    @staticmethod
    def _require_cp932_text(
        field_name: str,
        value: object,
        width: int,
        *,
        allow_blank: bool = True,
    ) -> None:
        if not isinstance(value, str) or (not allow_blank and value == ""):
            raise ValueError(f"HN {field_name} must be provider text")
        try:
            encoded = value.encode("cp932", errors="strict")
        except UnicodeEncodeError as error:
            raise ValueError(f"HN {field_name} is not CP932 encodable") from error
        if len(encoded) > width:
            raise ValueError(f"HN {field_name} exceeds its official {width}-byte span")

    @classmethod
    def validate_key_fields(cls, record: Mapping[str, object]) -> None:
        cls._require_date("MakeDate", record.get("MakeDate"))
        cls._require_ascii_digits("HansyokuNum", record.get("HansyokuNum"), 10)

    @classmethod
    def validate_current_fields(
        cls,
        record: Mapping[str, object],
        *,
        data_kubun: str | None = None,
    ) -> None:
        """Validate one current HN row before coercion or database mutation."""

        cls.validate_key_fields(record)
        status = data_kubun if data_kubun is not None else record.get("DataKubun")
        if status == "0":
            # An official delete command is defined by its exact identity. The
            # non-key provider bytes are deliberately not interpreted.
            return

        if record.get("reserved") != "00000000":
            raise ValueError("HN reserved must be the official initial value 00000000")
        if record.get("DelKubun") != "0":
            raise ValueError("HN DelKubun must be the official reserved value 0")
        for field_name in ("KettoNum", "FHansyokuNum", "MHansyokuNum"):
            cls._require_ascii_digits(field_name, record.get(field_name), 10)
        for field_name in ("BirthYear", "ImportYear"):
            cls._require_ascii_digits(field_name, record.get(field_name), 4)
        cls._require_ascii_digits("SexCD", record.get("SexCD"), 1)
        cls._require_ascii_digits("HinsyuCD", record.get("HinsyuCD"), 1)
        cls._require_ascii_digits("KeiroCD", record.get("KeiroCD"), 2)
        if record.get("MochiKubun") not in cls.MOCHI_KUBUN_VALUES:
            raise ValueError("HN MochiKubun is not an official code")
        for field_name, width in cls.TEXT_FIELD_WIDTHS.items():
            cls._require_cp932_text(
                field_name,
                record.get(field_name),
                width,
                allow_blank=(field_name != "Bamei"),
            )

    @classmethod
    def _validate_envelope(cls, data: bytes) -> tuple[str, str]:
        if len(data) != cls.RECORD_LENGTH:
            raise ValueError(
                f"HN record length mismatch: expected={(cls.RECORD_LENGTH,)}, actual={len(data)}"
            )
        if data[:2] != b"HN":
            raise ValueError(f"Record type mismatch: expected HN, got {data[:2]!r}")
        if data[-2:] != b"\r\n":
            raise ValueError("HN record delimiter must be CRLF")
        data_kubun = data[2:3].decode("ascii", errors="strict")
        make_date = data[3:11].decode("ascii", errors="strict")
        cls._require_date("MakeDate", make_date)
        status_domain.validate_data_kubun("HN", data_kubun, make_date=make_date)
        return data_kubun, make_date

    def parse(self, data: bytes) -> dict[str, object] | None:
        """
        HNレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            data_kubun, make_date = self._validate_envelope(data)
            # 現行DIFN/BLDNセットアップの251バイト物理形式だけを受理する。
            # 旧245バイト形式を現行offsetで部分抽出すると、主キーを含む全後続
            # フィールドが壊れるため、警告後の継続や長いrecordの黙認はしない。
            if len(data) != self.RECORD_LENGTH:
                self.logger.warning(
                    f"HNレコード長不正: expected={self.RECORD_LENGTH}, "
                    f"actual={len(data)}. 仕様世代の異なるレコードの可能性があるため破棄"
                )
                return None

            delimiter = data[self.RECORD_DELIMITER_START : self.RECORD_LENGTH]
            if delimiter != b"\r\n":
                self.logger.warning(
                    "HNレコードのレコード区切が CRLF ではない: "
                    f"pos={self.RECORD_DELIMITER_START} actual={delimiter!r}. "
                    "仕様世代の異なるレコードの可能性があるため破棄"
                )
                return None

            if data_kubun != "0":
                # Live rows must remain losslessly decodable as CP932. Delete
                # rows intentionally decode only the header and key below.
                data.decode("cp932", errors="strict")

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = data_kubun

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = make_date

            # 4. 繁殖登録番号 (位置:12, 長さ:10)
            result["HansyokuNum"] = self.decode_field(data[11:21])

            # 5. 予備 (位置:22, 長さ:8)
            result["reserved"] = "" if data_kubun == "0" else self.decode_field(data[21:29])

            # 6. 血統登録番号 (位置:30, 長さ:10)
            result["KettoNum"] = "" if data_kubun == "0" else self.decode_field(data[29:39])

            # 7. 繁殖馬抹消区分（現在は予備） (位置:40, 長さ:1)
            result["DelKubun"] = "" if data_kubun == "0" else self.decode_field(data[39:40])

            # 8. 馬名 (位置:41, 長さ:36)
            result["Bamei"] = "" if data_kubun == "0" else self.decode_field(data[40:76])

            # 9. 馬名半角ｶﾅ (位置:77, 長さ:40)
            result["BameiKana"] = "" if data_kubun == "0" else self.decode_field(data[76:116])

            # 10. 馬名欧字 (位置:117, 長さ:80)
            result["BameiEng"] = "" if data_kubun == "0" else self.decode_field(data[116:196])

            # 11. 生年 (位置:197, 長さ:4)
            result["BirthYear"] = "" if data_kubun == "0" else self.decode_field(data[196:200])

            # 12. 性別コード (位置:201, 長さ:1)
            result["SexCD"] = "" if data_kubun == "0" else self.decode_field(data[200:201])

            # 13. 品種コード (位置:202, 長さ:1)
            result["HinsyuCD"] = "" if data_kubun == "0" else self.decode_field(data[201:202])

            # 14. 毛色コード (位置:203, 長さ:2)
            result["KeiroCD"] = "" if data_kubun == "0" else self.decode_field(data[202:204])

            # 15. 繁殖馬持込区分 (位置:205, 長さ:1)
            result["MochiKubun"] = "" if data_kubun == "0" else self.decode_field(data[204:205])

            # 16. 輸入年 (位置:206, 長さ:4)
            result["ImportYear"] = "" if data_kubun == "0" else self.decode_field(data[205:209])

            # 17. 産地名 (位置:210, 長さ:20)
            result["SanchiName"] = "" if data_kubun == "0" else self.decode_field(data[209:229])

            # 18. 父馬繁殖登録番号 (位置:230, 長さ:10)
            result["FHansyokuNum"] = "" if data_kubun == "0" else self.decode_field(data[229:239])

            # 19. 母馬繁殖登録番号 (位置:240, 長さ:10)
            result["MHansyokuNum"] = "" if data_kubun == "0" else self.decode_field(data[239:249])

            # 20. レコード区切 (位置:250, 長さ:2)
            result["RecordDelimiter"] = (
                None if data_kubun == "0" else self.decode_field(data[249:251])
            )

            self.validate_current_fields(result, data_kubun=data_kubun)

            return result

        except Exception as e:
            self.logger.error(f"HNレコードパース中にエラー: {e}")
            return None
