#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
HRレコードパーサー: ４．払戻

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class HRParser:
    """
    HRレコードパーサー

    ４．払戻
    レコード長: 240 bytes
    VBテーブル名: HARAI
    """

    RECORD_TYPE = "HR"
    RECORD_LENGTH = 240

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        HRレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"HRレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Year"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["MonthDay"] = self.decode_field(data[15:19])

            # 6. 競馬場コード (位置:20, 長さ:2)
            result["JyoCD"] = self.decode_field(data[19:21])

            # 7. 開催回[第N回] (位置:22, 長さ:2)
            result["Kaiji"] = self.decode_field(data[21:23])

            # 8. 開催日目[N日目] (位置:24, 長さ:2)
            result["Nichiji"] = self.decode_field(data[23:25])

            # 9. レース番号 (位置:26, 長さ:2)
            result["RaceNum"] = self.decode_field(data[25:27])

            # 10. 登録頭数 (位置:28, 長さ:2)
            result["TorokuTosu"] = self.decode_field(data[27:29])

            # 11. 出走頭数 (位置:30, 長さ:2)
            result["SyussoTosu"] = self.decode_field(data[29:31])

            # 12. 不成立フラグ　単勝 (位置:32, 長さ:1)
            result["FuseirituFlag1"] = self.decode_field(data[31:32])

            # 13. 不成立フラグ　複勝 (位置:33, 長さ:1)
            result["FuseirituFlag2"] = self.decode_field(data[32:33])

            # 14. 不成立フラグ　枠連 (位置:34, 長さ:1)
            result["FuseirituFlag3"] = self.decode_field(data[33:34])

            # 15. 不成立フラグ　馬連 (位置:35, 長さ:1)
            result["FuseirituFlag4"] = self.decode_field(data[34:35])

            # 16. 不成立フラグ　ワイド (位置:36, 長さ:1)
            result["FuseirituFlag5"] = self.decode_field(data[35:36])

            # 17. 予備 (位置:37, 長さ:1)
            result["FuseirituFlag6"] = self.decode_field(data[36:37])

            # 18. 不成立フラグ　馬単 (位置:38, 長さ:1)
            result["FuseirituFlag7"] = self.decode_field(data[37:38])

            # 19. 不成立フラグ　3連複 (位置:39, 長さ:1)
            result["FuseirituFlag8"] = self.decode_field(data[38:39])

            # 20. 不成立フラグ　3連単 (位置:40, 長さ:1)
            result["FuseirituFlag9"] = self.decode_field(data[39:40])

            # 21. 特払フラグ　単勝 (位置:41, 長さ:1)
            result["TokubaraiFlag1"] = self.decode_field(data[40:41])

            # 22. 特払フラグ　複勝 (位置:42, 長さ:1)
            result["TokubaraiFlag2"] = self.decode_field(data[41:42])

            # 23. 特払フラグ　枠連 (位置:43, 長さ:1)
            result["TokubaraiFlag3"] = self.decode_field(data[42:43])

            # 24. 特払フラグ　馬連 (位置:44, 長さ:1)
            result["TokubaraiFlag4"] = self.decode_field(data[43:44])

            # 25. 特払フラグ　ワイド (位置:45, 長さ:1)
            result["TokubaraiFlag5"] = self.decode_field(data[44:45])

            # 26. 予備 (位置:46, 長さ:1)
            result["TokubaraiFlag6"] = self.decode_field(data[45:46])

            # 27. 特払フラグ　馬単 (位置:47, 長さ:1)
            result["TokubaraiFlag7"] = self.decode_field(data[46:47])

            # 28. 特払フラグ　3連複 (位置:48, 長さ:1)
            result["TokubaraiFlag8"] = self.decode_field(data[47:48])

            # 29. 特払フラグ　3連単 (位置:49, 長さ:1)
            result["TokubaraiFlag9"] = self.decode_field(data[48:49])

            # 30. 返還フラグ　単勝 (位置:50, 長さ:1)
            result["HenkanFlag1"] = self.decode_field(data[49:50])

            # 31. 返還フラグ　複勝 (位置:51, 長さ:1)
            result["HenkanFlag2"] = self.decode_field(data[50:51])

            # 32. 返還フラグ　枠連 (位置:52, 長さ:1)
            result["HenkanFlag3"] = self.decode_field(data[51:52])

            # 33. 返還フラグ　馬連 (位置:53, 長さ:1)
            result["HenkanFlag4"] = self.decode_field(data[52:53])

            # 34. 返還フラグ　ワイド (位置:54, 長さ:1)
            result["HenkanFlag5"] = self.decode_field(data[53:54])

            # 35. 予備 (位置:55, 長さ:1)
            result["HenkanFlag6"] = self.decode_field(data[54:55])

            # 36. 返還フラグ　馬単 (位置:56, 長さ:1)
            result["HenkanFlag7"] = self.decode_field(data[55:56])

            # 37. 返還フラグ　3連複 (位置:57, 長さ:1)
            result["HenkanFlag8"] = self.decode_field(data[56:57])

            # 38. 返還フラグ　3連単 (位置:58, 長さ:1)
            result["HenkanFlag9"] = self.decode_field(data[57:58])

            # 39-66. 返還馬番情報　馬番01～28 (位置:59-86, 各1バイト)
            result["HenkanUma1"] = self.decode_field(data[58:59])
            result["HenkanUma2"] = self.decode_field(data[59:60])
            result["HenkanUma3"] = self.decode_field(data[60:61])
            result["HenkanUma4"] = self.decode_field(data[61:62])
            result["HenkanUma5"] = self.decode_field(data[62:63])
            result["HenkanUma6"] = self.decode_field(data[63:64])
            result["HenkanUma7"] = self.decode_field(data[64:65])
            result["HenkanUma8"] = self.decode_field(data[65:66])
            result["HenkanUma9"] = self.decode_field(data[66:67])
            result["HenkanUma10"] = self.decode_field(data[67:68])
            result["HenkanUma11"] = self.decode_field(data[68:69])
            result["HenkanUma12"] = self.decode_field(data[69:70])
            result["HenkanUma13"] = self.decode_field(data[70:71])
            result["HenkanUma14"] = self.decode_field(data[71:72])
            result["HenkanUma15"] = self.decode_field(data[72:73])
            result["HenkanUma16"] = self.decode_field(data[73:74])
            result["HenkanUma17"] = self.decode_field(data[74:75])
            result["HenkanUma18"] = self.decode_field(data[75:76])
            result["HenkanUma19"] = self.decode_field(data[76:77])
            result["HenkanUma20"] = self.decode_field(data[77:78])
            result["HenkanUma21"] = self.decode_field(data[78:79])
            result["HenkanUma22"] = self.decode_field(data[79:80])
            result["HenkanUma23"] = self.decode_field(data[80:81])
            result["HenkanUma24"] = self.decode_field(data[81:82])
            result["HenkanUma25"] = self.decode_field(data[82:83])
            result["HenkanUma26"] = self.decode_field(data[83:84])
            result["HenkanUma27"] = self.decode_field(data[84:85])
            result["HenkanUma28"] = self.decode_field(data[85:86])

            # 67-74. 返還枠番情報　枠番1～8 (位置:87-94, 各1バイト)
            result["HenkanWaku1"] = self.decode_field(data[86:87])
            result["HenkanWaku2"] = self.decode_field(data[87:88])
            result["HenkanWaku3"] = self.decode_field(data[88:89])
            result["HenkanWaku4"] = self.decode_field(data[89:90])
            result["HenkanWaku5"] = self.decode_field(data[90:91])
            result["HenkanWaku6"] = self.decode_field(data[91:92])
            result["HenkanWaku7"] = self.decode_field(data[92:93])
            result["HenkanWaku8"] = self.decode_field(data[93:94])

            # 75-78. 返還同枠情報　枠番1～8 (位置:95-98, 各1バイト)
            result["HenkanDoWaku1"] = self.decode_field(data[94:95])
            result["HenkanDoWaku2"] = self.decode_field(data[95:96])
            result["HenkanDoWaku3"] = self.decode_field(data[96:97])
            result["HenkanDoWaku4"] = self.decode_field(data[97:98])

            # 79-81. 単勝払戻 (位置:99-109)
            result["TanUmaban"] = self.decode_field(data[98:100])
            result["TanPay"] = self.decode_field(data[100:109])
            result["TanNinki"] = self.decode_field(data[109:111])

            # 82-84. 複勝払戻 (位置:112-122)
            result["FukuUmaban"] = self.decode_field(data[111:113])
            result["FukuPay"] = self.decode_field(data[113:122])
            result["FukuNinki"] = self.decode_field(data[122:124])

            # 85-87. 枠連払戻 (位置:125-135)
            result["WakuKumi"] = self.decode_field(data[124:126])
            result["WakuPay"] = self.decode_field(data[126:135])
            result["WakuNinki"] = self.decode_field(data[135:137])

            # 88-90. 馬連払戻 (位置:138-150)
            result["UmarenKumi"] = self.decode_field(data[137:141])
            result["UmarenPay"] = self.decode_field(data[141:150])
            result["UmarenNinki"] = self.decode_field(data[150:153])

            # 91-93. ワイド払戻 (位置:154-166)
            result["WideKumi"] = self.decode_field(data[153:157])
            result["WidePay"] = self.decode_field(data[157:166])
            result["WideNinki"] = self.decode_field(data[166:169])

            # 94-96. 予備 (位置:170-182)
            result["Yobi1"] = self.decode_field(data[169:173])
            result["Yobi2"] = self.decode_field(data[173:182])
            result["Yobi3"] = self.decode_field(data[182:185])

            # 97-99. 馬単払戻 (位置:186-198)
            result["UmatanKumi"] = self.decode_field(data[185:189])
            result["UmatanPay"] = self.decode_field(data[189:198])
            result["UmatanNinki"] = self.decode_field(data[198:201])

            # 100-102. 3連複払戻 (位置:202-214)
            result["SanrenfukuKumi"] = self.decode_field(data[201:207])
            result["SanrenfukuPay"] = self.decode_field(data[207:216])
            result["SanrenfukuNinki"] = self.decode_field(data[216:219])

            # 103-105. 3連単払戻 (位置:220-232)
            result["SanrentanKumi"] = self.decode_field(data[219:225])
            result["SanrentanPay"] = self.decode_field(data[225:234])
            result["SanrentanNinki"] = self.decode_field(data[234:238])

            # 106. レコード区切 (位置:239-240)
            result["RecordDelimiter"] = self.decode_field(data[238:240])

            return result

        except Exception as e:
            self.logger.error(f"HRレコードパース中にエラー: {e}")
            return None
