#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
HRレコードパーサー: ４．払戻

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class HRParser:
    """
    HRレコードパーサー

    ４．払戻
    レコード長: 203 bytes
    VBテーブル名: HARAI
    """

    RECORD_TYPE = "HR"
    RECORD_LENGTH = 203

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        HRレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"HRレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Year"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["MonthDay"] = self.decode_field(data[15:19])

            # 6. 競馬場コード (位置:20, 長さ:2)
            result["JyoCD"] = self.decode_field(data[19:21])

            # 7. 開催回[第N回] (位置:22, 長さ:2)
            result["Kaiji"] = self.decode_field(data[21:23])

            # 8. 開催日目[N日目] (位置:24, 長さ:2)
            result["Nichiji"] = self.decode_field(data[23:25])

            # 9. レース番号 (位置:26, 長さ:2)
            result["RaceNum"] = self.decode_field(data[25:27])

            # 10. 登録頭数 (位置:28, 長さ:2)
            result["TorokuTosu"] = self.decode_field(data[27:29])

            # 11. 出走頭数 (位置:30, 長さ:2)
            result["SyussoTosu"] = self.decode_field(data[29:31])

            # 12. 不成立フラグ　単勝 (位置:32, 長さ:1)
            result["FuseirituFlag1"] = self.decode_field(data[31:32])

            # 13. 不成立フラグ　複勝 (位置:33, 長さ:1)
            result["FuseirituFlag2"] = self.decode_field(data[32:33])

            # 14. 不成立フラグ　枠連 (位置:34, 長さ:1)
            result["FuseirituFlag3"] = self.decode_field(data[33:34])

            # 15. 不成立フラグ　馬連 (位置:35, 長さ:1)
            result["FuseirituFlag4"] = self.decode_field(data[34:35])

            # 16. 不成立フラグ　ワイド (位置:36, 長さ:1)
            result["FuseirituFlag5"] = self.decode_field(data[35:36])

            # 17. 予備 (位置:37, 長さ:1)
            result["FuseirituFlag6"] = self.decode_field(data[36:37])

            # 18. 不成立フラグ　馬単 (位置:38, 長さ:1)
            result["FuseirituFlag7"] = self.decode_field(data[37:38])

            # 19. 不成立フラグ　3連複 (位置:39, 長さ:1)
            result["FuseirituFlag8"] = self.decode_field(data[38:39])

            # 20. 不成立フラグ　3連単 (位置:40, 長さ:1)
            result["FuseirituFlag9"] = self.decode_field(data[39:40])

            # 21. 特払フラグ　単勝 (位置:41, 長さ:1)
            result["TokubaraiFlag1"] = self.decode_field(data[40:41])

            # 22. 特払フラグ　複勝 (位置:42, 長さ:1)
            result["TokubaraiFlag2"] = self.decode_field(data[41:42])

            # 23. 特払フラグ　枠連 (位置:43, 長さ:1)
            result["TokubaraiFlag3"] = self.decode_field(data[42:43])

            # 24. 特払フラグ　馬連 (位置:44, 長さ:1)
            result["TokubaraiFlag4"] = self.decode_field(data[43:44])

            # 25. 特払フラグ　ワイド (位置:45, 長さ:1)
            result["TokubaraiFlag5"] = self.decode_field(data[44:45])

            # 26. 予備 (位置:46, 長さ:1)
            result["TokubaraiFlag6"] = self.decode_field(data[45:46])

            # 27. 特払フラグ　馬単 (位置:47, 長さ:1)
            result["TokubaraiFlag7"] = self.decode_field(data[46:47])

            # 28. 特払フラグ　3連複 (位置:48, 長さ:1)
            result["TokubaraiFlag8"] = self.decode_field(data[47:48])

            # 29. 特払フラグ　3連単 (位置:49, 長さ:1)
            result["TokubaraiFlag9"] = self.decode_field(data[48:49])

            # 30. 返還フラグ　単勝 (位置:50, 長さ:1)
            result["HenkanFlag1"] = self.decode_field(data[49:50])

            # 31. 返還フラグ　複勝 (位置:51, 長さ:1)
            result["HenkanFlag2"] = self.decode_field(data[50:51])

            # 32. 返還フラグ　枠連 (位置:52, 長さ:1)
            result["HenkanFlag3"] = self.decode_field(data[51:52])

            # 33. 返還フラグ　馬連 (位置:53, 長さ:1)
            result["HenkanFlag4"] = self.decode_field(data[52:53])

            # 34. 返還フラグ　ワイド (位置:54, 長さ:1)
            result["HenkanFlag5"] = self.decode_field(data[53:54])

            # 35. 予備 (位置:55, 長さ:1)
            result["HenkanFlag6"] = self.decode_field(data[54:55])

            # 36. 返還フラグ　馬単 (位置:56, 長さ:1)
            result["HenkanFlag7"] = self.decode_field(data[55:56])

            # 37. 返還フラグ　3連複 (位置:57, 長さ:1)
            result["HenkanFlag8"] = self.decode_field(data[56:57])

            # 38. 返還フラグ　3連単 (位置:58, 長さ:1)
            result["HenkanFlag9"] = self.decode_field(data[57:58])

            # 39. 返還馬番情報(馬番01～28) (位置:59, 長さ:1)
            result["HenkanUma1"] = self.decode_field(data[58:59])

            # 40. 返還枠番情報(枠番1～8) (位置:60, 長さ:1)
            result["HenkanUma2"] = self.decode_field(data[59:60])

            # 41. 返還同枠情報(枠番1～8) (位置:61, 長さ:1)
            result["HenkanUma3"] = self.decode_field(data[60:61])

            # 42. <単勝払戻> (位置:62, 長さ:0)
            result["HenkanUma4"] = self.decode_field(data[61:61])

            # 43. 　　馬番 (位置:62, 長さ:2)
            result["HenkanUma5"] = self.decode_field(data[61:63])

            # 44. 　　払戻金 (位置:64, 長さ:9)
            result["HenkanUma6"] = self.decode_field(data[63:72])

            # 45. 　　人気順 (位置:73, 長さ:2)
            result["HenkanUma7"] = self.decode_field(data[72:74])

            # 46. <複勝払戻> (位置:75, 長さ:0)
            result["HenkanUma8"] = self.decode_field(data[74:74])

            # 47. 　　馬番 (位置:75, 長さ:2)
            result["HenkanUma9"] = self.decode_field(data[74:76])

            # 48. 　　払戻金 (位置:77, 長さ:9)
            result["HenkanUma10"] = self.decode_field(data[76:85])

            # 49. 　　人気順 (位置:86, 長さ:2)
            result["HenkanUma11"] = self.decode_field(data[85:87])

            # 50. <枠連払戻> (位置:88, 長さ:0)
            result["HenkanUma12"] = self.decode_field(data[87:87])

            # 51. 　　組番 (位置:88, 長さ:2)
            result["HenkanUma13"] = self.decode_field(data[87:89])

            # 52. 　　払戻金 (位置:90, 長さ:9)
            result["HenkanUma14"] = self.decode_field(data[89:98])

            # 53. 　　人気順 (位置:99, 長さ:2)
            result["HenkanUma15"] = self.decode_field(data[98:100])

            # 54. <馬連払戻> (位置:101, 長さ:0)
            result["HenkanUma16"] = self.decode_field(data[100:100])

            # 55. 　　組番 (位置:101, 長さ:4)
            result["HenkanUma17"] = self.decode_field(data[100:104])

            # 56. 　　払戻金 (位置:105, 長さ:9)
            result["HenkanUma18"] = self.decode_field(data[104:113])

            # 57. 　　人気順 (位置:114, 長さ:3)
            result["HenkanUma19"] = self.decode_field(data[113:116])

            # 58. <ワイド払戻> (位置:117, 長さ:0)
            result["HenkanUma20"] = self.decode_field(data[116:116])

            # 59. 　　組番 (位置:117, 長さ:4)
            result["HenkanUma21"] = self.decode_field(data[116:120])

            # 60. 　　払戻金 (位置:121, 長さ:9)
            result["HenkanUma22"] = self.decode_field(data[120:129])

            # 61. 　　人気順 (位置:130, 長さ:3)
            result["HenkanUma23"] = self.decode_field(data[129:132])

            # 62. <予備> (位置:133, 長さ:0)
            result["HenkanUma24"] = self.decode_field(data[132:132])

            # 63. 　　予備 (位置:133, 長さ:4)
            result["HenkanUma25"] = self.decode_field(data[132:136])

            # 64. 　　予備 (位置:137, 長さ:9)
            result["HenkanUma26"] = self.decode_field(data[136:145])

            # 65. 　　予備 (位置:146, 長さ:3)
            result["HenkanUma27"] = self.decode_field(data[145:148])

            # 66. <馬単払戻> (位置:149, 長さ:0)
            result["HenkanUma28"] = self.decode_field(data[148:148])

            # 67. 　　組番 (位置:149, 長さ:4)
            result["HenkanWaku1"] = self.decode_field(data[148:152])

            # 68. 　　払戻金 (位置:153, 長さ:9)
            result["HenkanWaku2"] = self.decode_field(data[152:161])

            # 69. 　　人気順 (位置:162, 長さ:3)
            result["HenkanWaku3"] = self.decode_field(data[161:164])

            # 70. <3連複払戻> (位置:165, 長さ:0)
            result["HenkanWaku4"] = self.decode_field(data[164:164])

            # 71. 　　組番 (位置:165, 長さ:6)
            result["HenkanWaku5"] = self.decode_field(data[164:170])

            # 72. 　　払戻金 (位置:171, 長さ:9)
            result["HenkanWaku6"] = self.decode_field(data[170:179])

            # 73. 　　人気順 (位置:180, 長さ:3)
            result["HenkanWaku7"] = self.decode_field(data[179:182])

            # 74. <3連単払戻> (位置:183, 長さ:0)
            result["HenkanWaku8"] = self.decode_field(data[182:182])

            # 75. 　　組番 (位置:183, 長さ:6)
            result["HenkanDoWaku1"] = self.decode_field(data[182:188])

            # 76. 　　払戻金 (位置:189, 長さ:9)
            result["HenkanDoWaku2"] = self.decode_field(data[188:197])

            # 77. 　　人気順 (位置:198, 長さ:4)
            result["HenkanDoWaku3"] = self.decode_field(data[197:201])

            # 78. レコード区切 (位置:202, 長さ:2)
            result["HenkanDoWaku4"] = self.decode_field(data[201:203])

            return result

        except Exception as e:
            self.logger.error(f"HRレコードパース中にエラー: {e}")
            return None
