#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
KSレコードパーサー: １４．騎手マスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class KSParser:
    """
    KSレコードパーサー

    １４．騎手マスタ
    レコード長: 772 bytes
    VBテーブル名: KISYU
    """

    RECORD_TYPE = "KS"
    RECORD_LENGTH = 772

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        KSレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"KSレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 騎手コード (位置:12, 長さ:5)
            result["DelKubun"] = self.decode_field(data[11:16])

            # 5. 騎手抹消区分 (位置:17, 長さ:1)
            result["IssueDate"] = self.decode_field(data[16:17])

            # 6. 騎手免許交付年月日 (位置:18, 長さ:8)
            result["DelDate"] = self.decode_field(data[17:25])

            # 7. 騎手免許抹消年月日 (位置:26, 長さ:8)
            result["BirthDate"] = self.decode_field(data[25:33])

            # 8. 生年月日 (位置:34, 長さ:8)
            result["KisyuName"] = self.decode_field(data[33:41])

            # 9. 騎手名 (位置:42, 長さ:34)
            result["reserved"] = self.decode_field(data[41:75])

            # 10. 予備 (位置:76, 長さ:34)
            result["KisyuNameKana"] = self.decode_field(data[75:109])

            # 11. 騎手名半角ｶﾅ (位置:110, 長さ:30)
            result["KisyuRyakusyo"] = self.decode_field(data[109:139])

            # 12. 騎手名略称 (位置:140, 長さ:8)
            result["KisyuNameEng"] = self.decode_field(data[139:147])

            # 13. 騎手名欧字 (位置:148, 長さ:80)
            result["SexCD"] = self.decode_field(data[147:227])

            # 14. 性別区分 (位置:228, 長さ:1)
            result["SikakuCD"] = self.decode_field(data[227:228])

            # 15. 騎乗資格コード (位置:229, 長さ:1)
            result["MinaraiCD"] = self.decode_field(data[228:229])

            # 16. 騎手見習コード (位置:230, 長さ:1)
            result["TozaiCD"] = self.decode_field(data[229:230])

            # 17. 騎手東西所属コード (位置:231, 長さ:1)
            result["Syotai"] = self.decode_field(data[230:231])

            # 18. 招待地域名 (位置:232, 長さ:20)
            result["ChokyosiCode"] = self.decode_field(data[231:251])

            # 19. 所属調教師コード (位置:252, 長さ:5)
            result["ChokyosiRyakusyo"] = self.decode_field(data[251:256])

            # 20. 所属調教師名略称 (位置:257, 長さ:8)
            result["HatuKiJyo1Hatukijyoid"] = self.decode_field(data[256:264])

            # 21. <初騎乗情報> (位置:265, 長さ:0)
            result["HatuKiJyo1SyussoTosu"] = self.decode_field(data[264:264])

            # 22. 　　年月日場回日R (位置:265, 長さ:16)
            result["HatuKiJyo1KettoNum"] = self.decode_field(data[264:280])

            # 23. 　　出走頭数 (位置:281, 長さ:2)
            result["HatuKiJyo1Bamei"] = self.decode_field(data[280:282])

            # 24. 　　血統登録番号 (位置:283, 長さ:10)
            result["HatuKiJyo1KakuteiJyuni"] = self.decode_field(data[282:292])

            # 25. 　　馬名 (位置:293, 長さ:36)
            result["HatuKiJyo1IJyoCD"] = self.decode_field(data[292:328])

            # 26. 　　確定着順 (位置:329, 長さ:2)
            result["HatuKiJyo2Hatukijyoid"] = self.decode_field(data[328:330])

            # 27. 　　異常区分コード (位置:331, 長さ:1)
            result["HatuKiJyo2SyussoTosu"] = self.decode_field(data[330:331])

            # 28. <初勝利情報> (位置:332, 長さ:0)
            result["HatuKiJyo2KettoNum"] = self.decode_field(data[331:331])

            # 29. 　　年月日場回日R (位置:332, 長さ:16)
            result["HatuKiJyo2Bamei"] = self.decode_field(data[331:347])

            # 30. 　　出走頭数 (位置:348, 長さ:2)
            result["HatuKiJyo2KakuteiJyuni"] = self.decode_field(data[347:349])

            # 31. 　　血統登録番号 (位置:350, 長さ:10)
            result["HatuKiJyo2IJyoCD"] = self.decode_field(data[349:359])

            # 32. 　　馬名 (位置:360, 長さ:36)
            result["HatuSyori1Hatusyoriid"] = self.decode_field(data[359:395])

            # 33. <最近重賞勝利情報> (位置:396, 長さ:0)
            result["HatuSyori1SyussoTosu"] = self.decode_field(data[395:395])

            # 34. 　　年月日場回日R (位置:396, 長さ:16)
            result["HatuSyori1KettoNum"] = self.decode_field(data[395:411])

            # 35. 　　競走名本題 (位置:412, 長さ:60)
            result["HatuSyori1Bamei"] = self.decode_field(data[411:471])

            # 36. 　　競走名略称10文字 (位置:472, 長さ:20)
            result["HatuSyori2Hatusyoriid"] = self.decode_field(data[471:491])

            # 37. 　　競走名略称6文字 (位置:492, 長さ:12)
            result["HatuSyori2SyussoTosu"] = self.decode_field(data[491:503])

            # 38. 　　競走名略称3文字 (位置:504, 長さ:6)
            result["HatuSyori2KettoNum"] = self.decode_field(data[503:509])

            # 39. 　　グレードコード (位置:510, 長さ:1)
            result["HatuSyori2Bamei"] = self.decode_field(data[509:510])

            # 40. 　　出走頭数 (位置:511, 長さ:2)
            result["SaikinJyusyo1SaikinJyusyoid"] = self.decode_field(data[510:512])

            # 41. 　　血統登録番号 (位置:513, 長さ:10)
            result["SaikinJyusyo1Hondai"] = self.decode_field(data[512:522])

            # 42. 　　馬名 (位置:523, 長さ:36)
            result["SaikinJyusyo1Ryakusyo10"] = self.decode_field(data[522:558])

            # 43. <本年･前年･累計成績情報> (位置:559, 長さ:0)
            result["SaikinJyusyo1Ryakusyo6"] = self.decode_field(data[558:558])

            # 44. 　　設定年 (位置:559, 長さ:4)
            result["SaikinJyusyo1Ryakusyo3"] = self.decode_field(data[558:562])

            # 45. 　　平地本賞金合計 (位置:563, 長さ:10)
            result["SaikinJyusyo1GradeCD"] = self.decode_field(data[562:572])

            # 46. 　　障害本賞金合計 (位置:573, 長さ:10)
            result["SaikinJyusyo1SyussoTosu"] = self.decode_field(data[572:582])

            # 47. 　　平地付加賞金合計 (位置:583, 長さ:10)
            result["SaikinJyusyo1KettoNum"] = self.decode_field(data[582:592])

            # 48. 　　障害付加賞金合計 (位置:593, 長さ:10)
            result["SaikinJyusyo1Bamei"] = self.decode_field(data[592:602])

            # 49. 　　平地着回数 (位置:603, 長さ:6)
            result["SaikinJyusyo2SaikinJyusyoid"] = self.decode_field(data[602:608])

            # 50. 　　障害着回数 (位置:609, 長さ:6)
            result["SaikinJyusyo2Hondai"] = self.decode_field(data[608:614])

            # 51. 　　<競馬場別着回数> (位置:615, 長さ:0)
            result["SaikinJyusyo2Ryakusyo10"] = self.decode_field(data[614:614])

            # 52. 　　札幌平地着回数 (位置:615, 長さ:6)
            result["SaikinJyusyo2Ryakusyo6"] = self.decode_field(data[614:620])

            # 53. 　　札幌障害着回数 (位置:621, 長さ:6)
            result["SaikinJyusyo2Ryakusyo3"] = self.decode_field(data[620:626])

            # 54. 　　函館平地着回数 (位置:627, 長さ:6)
            result["SaikinJyusyo2GradeCD"] = self.decode_field(data[626:632])

            # 55. 　　函館障害着回数 (位置:633, 長さ:6)
            result["SaikinJyusyo2SyussoTosu"] = self.decode_field(data[632:638])

            # 56. 　　福島平地着回数 (位置:639, 長さ:6)
            result["SaikinJyusyo2KettoNum"] = self.decode_field(data[638:644])

            # 57. 　　福島障害着回数 (位置:645, 長さ:6)
            result["SaikinJyusyo2Bamei"] = self.decode_field(data[644:650])

            # 58. 　　新潟平地着回数 (位置:651, 長さ:6)
            result["SaikinJyusyo3SaikinJyusyoid"] = self.decode_field(data[650:656])

            # 59. 　　新潟障害着回数 (位置:657, 長さ:6)
            result["SaikinJyusyo3Hondai"] = self.decode_field(data[656:662])

            # 60. 　　東京平地着回数 (位置:663, 長さ:6)
            result["SaikinJyusyo3Ryakusyo10"] = self.decode_field(data[662:668])

            # 61. 　　東京障害着回数 (位置:669, 長さ:6)
            result["SaikinJyusyo3Ryakusyo6"] = self.decode_field(data[668:674])

            # 62. 　　中山平地着回数 (位置:675, 長さ:6)
            result["SaikinJyusyo3Ryakusyo3"] = self.decode_field(data[674:680])

            # 63. 　　中山障害着回数 (位置:681, 長さ:6)
            result["SaikinJyusyo3GradeCD"] = self.decode_field(data[680:686])

            # 64. 　　中京平地着回数 (位置:687, 長さ:6)
            result["SaikinJyusyo3SyussoTosu"] = self.decode_field(data[686:692])

            # 65. 　　中京障害着回数 (位置:693, 長さ:6)
            result["SaikinJyusyo3KettoNum"] = self.decode_field(data[692:698])

            # 66. 　　京都平地着回数 (位置:699, 長さ:6)
            result["Field66"] = self.decode_field(data[698:704])

            # 67. 　　京都障害着回数 (位置:705, 長さ:6)
            result["Field67"] = self.decode_field(data[704:710])

            # 68. 　　阪神平地着回数 (位置:711, 長さ:6)
            result["Field68"] = self.decode_field(data[710:716])

            # 69. 　　阪神障害着回数 (位置:717, 長さ:6)
            result["Field69"] = self.decode_field(data[716:722])

            # 70. 　　小倉平地着回数 (位置:723, 長さ:6)
            result["Field70"] = self.decode_field(data[722:728])

            # 71. 　　小倉障害着回数 (位置:729, 長さ:6)
            result["Field71"] = self.decode_field(data[728:734])

            # 72. 　　<距離別着回数> (位置:735, 長さ:0)
            result["Field72"] = self.decode_field(data[734:734])

            # 73. 　　芝16下・着回数 (位置:735, 長さ:6)
            result["Field73"] = self.decode_field(data[734:740])

            # 74. 　　芝22下・着回数 (位置:741, 長さ:6)
            result["Field74"] = self.decode_field(data[740:746])

            # 75. 　　芝22超・着回数 (位置:747, 長さ:6)
            result["Field75"] = self.decode_field(data[746:752])

            # 76. 　　ダ16下・着回数 (位置:753, 長さ:6)
            result["Field76"] = self.decode_field(data[752:758])

            # 77. 　　ダ22下・着回数 (位置:759, 長さ:6)
            result["Field77"] = self.decode_field(data[758:764])

            # 78. 　　ダ22超・着回数 (位置:765, 長さ:6)
            result["Field78"] = self.decode_field(data[764:770])

            # 79. レコード区切 (位置:771, 長さ:2)
            result["Field79"] = self.decode_field(data[770:772])

            return result

        except Exception as e:
            self.logger.error(f"KSレコードパース中にエラー: {e}")
            return None
