#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
O1レコードパーサー: ７．オッズ1（単複枠）

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class O1Parser:
    """
    O1レコードパーサー

    ７．オッズ1（単複枠）
    レコード長: 107 bytes
    VBテーブル名: ODDS_TANPUKU
    """

    RECORD_TYPE = "O1"
    RECORD_LENGTH = 107

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        O1レコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"O1レコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["MakeDate"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["Year"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MonthDay"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["JyoCD"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["Kaiji"] = self.decode_field(data[15:19])

            # 6. 競馬場コード (位置:20, 長さ:2)
            result["Nichiji"] = self.decode_field(data[19:21])

            # 7. 開催回[第N回] (位置:22, 長さ:2)
            result["RaceNum"] = self.decode_field(data[21:23])

            # 8. 開催日目[N日目] (位置:24, 長さ:2)
            result["Umaban"] = self.decode_field(data[23:25])

            # 9. レース番号 (位置:26, 長さ:2)
            result["TanOdds"] = self.decode_field(data[25:27])

            # 10. 発表月日時分 (位置:28, 長さ:8)
            result["TanNinki"] = self.decode_field(data[27:35])

            # 11. 登録頭数 (位置:36, 長さ:2)
            result["FukuOddsLow"] = self.decode_field(data[35:37])

            # 12. 出走頭数 (位置:38, 長さ:2)
            result["FukuOddsHigh"] = self.decode_field(data[37:39])

            # 13. 発売フラグ　単勝 (位置:40, 長さ:1)
            result["FukuNinki"] = self.decode_field(data[39:40])

            # 14. 発売フラグ　複勝 (位置:41, 長さ:1)
            result["Field14"] = self.decode_field(data[40:41])

            # 15. 発売フラグ　枠連 (位置:42, 長さ:1)
            result["Field15"] = self.decode_field(data[41:42])

            # 16. 複勝着払キー (位置:43, 長さ:1)
            result["Field16"] = self.decode_field(data[42:43])

            # 17. <単勝オッズ> (位置:44, 長さ:0)
            result["Field17"] = self.decode_field(data[43:43])

            # 18. 　　馬番 (位置:44, 長さ:2)
            result["Field18"] = self.decode_field(data[43:45])

            # 19. 　　オッズ (位置:46, 長さ:4)
            result["Field19"] = self.decode_field(data[45:49])

            # 20. 　　人気順 (位置:50, 長さ:2)
            result["Field20"] = self.decode_field(data[49:51])

            # 21. <複勝オッズ> (位置:52, 長さ:0)
            result["Field21"] = self.decode_field(data[51:51])

            # 22. 　　馬番 (位置:52, 長さ:2)
            result["Field22"] = self.decode_field(data[51:53])

            # 23. 　　最低オッズ (位置:54, 長さ:4)
            result["Field23"] = self.decode_field(data[53:57])

            # 24. 　　最高オッズ (位置:58, 長さ:4)
            result["Field24"] = self.decode_field(data[57:61])

            # 25. 　　人気順 (位置:62, 長さ:2)
            result["Field25"] = self.decode_field(data[61:63])

            # 26. <枠連オッズ> (位置:64, 長さ:0)
            result["Field26"] = self.decode_field(data[63:63])

            # 27. 　　組番 (位置:64, 長さ:2)
            result["Field27"] = self.decode_field(data[63:65])

            # 28. 　　オッズ (位置:66, 長さ:5)
            result["Field28"] = self.decode_field(data[65:70])

            # 29. 　　人気順 (位置:71, 長さ:2)
            result["Field29"] = self.decode_field(data[70:72])

            # 30. 単勝票数合計 (位置:73, 長さ:11)
            result["Field30"] = self.decode_field(data[72:83])

            # 31. 複勝票数合計 (位置:84, 長さ:11)
            result["Field31"] = self.decode_field(data[83:94])

            # 32. 枠連票数合計 (位置:95, 長さ:11)
            result["Field32"] = self.decode_field(data[94:105])

            # 33. レコード区切 (位置:106, 長さ:2)
            result["Field33"] = self.decode_field(data[105:107])

            return result

        except Exception as e:
            self.logger.error(f"O1レコードパース中にエラー: {e}")
            return None
