#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
O1レコードパーサー: ７．オッズ1（単複枠）

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, List, Optional
from src.utils.logger import get_logger


class O1Parser:
    """
    O1レコードパーサー

    ７．オッズ1（単複枠）
    レコード長: 107 bytes
    VBテーブル名: ODDS_TANPUKU
    """

    RECORD_TYPE = "O1"
    RECORD_LENGTH = 107

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[List[Dict[str, str]]]:
        """
        O1レコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"O1レコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            base = {
                "RecordSpec": self.decode_field(data[0:2]),
                "DataKubun": self.decode_field(data[2:3]),
                "MakeDate": self.decode_field(data[3:11]),
                "Year": self.decode_field(data[11:15]),
                "MonthDay": self.decode_field(data[15:19]),
                "JyoCD": self.decode_field(data[19:21]),
                "Kaiji": self.decode_field(data[21:23]),
                "Nichiji": self.decode_field(data[23:25]),
                "RaceNum": self.decode_field(data[25:27]),
                "HassoTime": self.decode_field(data[27:35]),
                "TorokuTosu": self.decode_field(data[35:37]),
                "SyussoTosu": self.decode_field(data[37:39]),
                "TanFlag": self.decode_field(data[39:40]),
                "FukuFlag": self.decode_field(data[40:41]),
                "WakurenFlag": self.decode_field(data[41:42]),
                "FukuChakubaraiKey": self.decode_field(data[42:43]),
            }

            # O1 has fixed arrays: 28 tan, 28 fuku, 36 wakuren, then 3 vote totals.
            tan_start = 43
            fuku_start = tan_start + 28 * 8
            wakuren_start = fuku_start + 28 * 12
            votes_start = wakuren_start + 36 * 9
            tan_vote = self.decode_field(data[votes_start:votes_start + 11])
            fuku_vote = self.decode_field(data[votes_start + 11:votes_start + 22])
            wakuren_vote = self.decode_field(data[votes_start + 22:votes_start + 33])

            rows_by_umaban: Dict[str, Dict[str, str]] = {}
            for i in range(28):
                pos = tan_start + i * 8
                item = data[pos:pos + 8]
                if len(item) < 8:
                    continue
                umaban = self.decode_field(item[0:2])
                odds = self.decode_field(item[2:6])
                ninki = self.decode_field(item[6:8])
                if not umaban.strip("0 "):
                    continue
                rows_by_umaban.setdefault(
                    umaban,
                    {**base, "Umaban": umaban, "FukuUmaban": umaban, "Kumi": ""},
                )
                rows_by_umaban[umaban].update(
                    {"TanOdds": odds, "TanNinki": ninki, "TanVote": tan_vote}
                )

            for i in range(28):
                pos = fuku_start + i * 12
                item = data[pos:pos + 12]
                if len(item) < 12:
                    continue
                umaban = self.decode_field(item[0:2])
                low = self.decode_field(item[2:6])
                high = self.decode_field(item[6:10])
                ninki = self.decode_field(item[10:12])
                if not umaban.strip("0 "):
                    continue
                rows_by_umaban.setdefault(
                    umaban,
                    {**base, "Umaban": umaban, "FukuUmaban": umaban, "Kumi": ""},
                )
                rows_by_umaban[umaban].update(
                    {
                        "FukuUmaban": umaban,
                        "FukuOddsLow": low,
                        "FukuOddsHigh": high,
                        "FukuNinki": ninki,
                        "FukuVote": fuku_vote,
                    }
                )

            rows = list(rows_by_umaban.values())
            for i in range(36):
                pos = wakuren_start + i * 9
                item = data[pos:pos + 9]
                if len(item) < 9:
                    continue
                kumi = self.decode_field(item[0:2])
                odds = self.decode_field(item[2:7])
                ninki = self.decode_field(item[7:9])
                if not kumi.strip("0 ") or not odds.strip("0 "):
                    continue
                rows.append(
                    {
                        **base,
                        "Umaban": "0",
                        "FukuUmaban": "",
                        "Kumi": kumi,
                        "WakurenOdds": odds,
                        "WakurenNinki": ninki,
                        "WakurenVote": wakuren_vote,
                    }
                )

            return rows

        except Exception as e:
            self.logger.error(f"O1レコードパース中にエラー: {e}")
            return None
