#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
O1レコードパーサー: ７．オッズ1（単複枠）

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, List, Mapping, Optional

from src.parser import odds_domain
from src.parser.base import validate_fixed_record
from src.utils.logger import get_logger


class O1Parser:
    """
    O1レコードパーサー

    ７．オッズ1（単複枠）
    レコード長: 962 bytes
    VBテーブル名: ODDS_TANPUKU
    """

    RECORD_TYPE = "O1"
    RECORD_LENGTH = 962

    # 公式のデータ区分・発売フラグ・オッズ部の桁数（JV-Data 4.9.0.1）
    DATA_KUBUN_VALUES = odds_domain.DATA_KUBUN_VALUES
    SALE_FLAG_VALUES = odds_domain.SALE_FLAG_VALUES
    SALE_FLAG_FIELDS = ("TanFlag", "FukuFlag", "WakurenFlag")
    # 複勝着払キー（0:複勝発売なし 2:2着まで払い 3:3着まで払い）
    PLACE_PAYOUT_KEY_VALUES = odds_domain.PLACE_PAYOUT_KEY_VALUES
    HORSE_NUMBER_WIDTH = 2
    BRACKET_COMBINATION_WIDTH = 2
    # 単勝28×8・複勝28×12・枠連36×9（オッズ部の繰返し）
    WIN_ENTRY_COUNT = 28
    PLACE_ENTRY_COUNT = 28
    BRACKET_ENTRY_COUNT = 36
    WIN_ODDS_WIDTHS = (("TanOdds", 4), ("TanNinki", 2))
    PLACE_ODDS_WIDTHS = (("FukuOddsLow", 4), ("FukuOddsHigh", 4), ("FukuNinki", 2))
    BRACKET_ODDS_WIDTHS = (("WakurenOdds", 5), ("WakurenNinki", 2))
    TOTAL_FIELDS = ("TanVote", "FukuVote", "WakurenVote")
    # 単複行は組番を持たないため "00"、枠連行は馬番を持たないため "0" を置く。
    HORSE_ROW_COMBINATION = "00"
    BRACKET_ROW_HORSE_NUMBER = "0"
    # 組合せを持たない snapshot でも公式の票数合計を保持する sentinel
    TOTAL_COMBINATION = odds_domain.TOTAL_COMBINATION

    @classmethod
    def validate_key_fields(cls, record: Mapping[str, object]) -> None:
        odds_domain.validate_key_fields(cls.RECORD_TYPE, record)

    @classmethod
    def _validate_present(
        cls,
        record: Mapping[str, object],
        widths: tuple[tuple[str, int], ...],
    ) -> None:
        """Validate the odds/favourite fields the row actually carries.

        単勝のみ・複勝のみが提供される snapshot があるため、提供されていない
        項目は検証対象にしない。提供された項目は公式の桁数と記号値に従う。
        """

        for field_name, width in widths:
            if field_name in record:
                odds_domain.require_marker_or_digits(
                    cls.RECORD_TYPE, field_name, record.get(field_name), width
                )

    @classmethod
    def validate_current_fields(
        cls,
        record: Mapping[str, object],
        *,
        data_kubun: str | None = None,
    ) -> None:
        """Validate one expanded O1 row against the official domain."""

        status = data_kubun if data_kubun is not None else record.get("DataKubun")
        if status not in cls.DATA_KUBUN_VALUES:
            raise ValueError("O1 DataKubun is not an official code")
        cls.validate_key_fields(record)
        if status == "0":
            # 削除指示は本文もヘッダも持たないため、レースキーだけを検証する。
            return

        odds_domain.validate_header_fields(
            cls.RECORD_TYPE,
            record,
            sale_flag_fields=cls.SALE_FLAG_FIELDS,
            total_fields=cls.TOTAL_FIELDS,
        )
        if record.get("FukuChakubaraiKey") not in cls.PLACE_PAYOUT_KEY_VALUES:
            raise ValueError("O1 FukuChakubaraiKey is not an official place payout key")

        combination = record.get("Kumi")
        if combination == cls.TOTAL_COMBINATION:
            odds_domain.validate_totals_only_row(
                cls.RECORD_TYPE,
                record,
                body_fields=tuple(
                    field_name
                    for field_name, _ in (
                        *cls.WIN_ODDS_WIDTHS,
                        *cls.PLACE_ODDS_WIDTHS,
                        *cls.BRACKET_ODDS_WIDTHS,
                    )
                ),
            )
            return
        if combination == cls.HORSE_ROW_COMBINATION:
            odds_domain.require_ascii_digits(
                cls.RECORD_TYPE, "Umaban", record.get("Umaban"), cls.HORSE_NUMBER_WIDTH
            )
            cls._validate_present(record, cls.WIN_ODDS_WIDTHS)
            cls._validate_present(record, cls.PLACE_ODDS_WIDTHS)
            return
        odds_domain.require_ascii_digits(
            cls.RECORD_TYPE, "Kumi", combination, cls.BRACKET_COMBINATION_WIDTH
        )
        cls._validate_present(record, cls.BRACKET_ODDS_WIDTHS)

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        return data.decode("cp932", errors="strict").strip()

    def parse(self, data: bytes) -> Optional[List[Dict[str, str]]]:
        """
        O1レコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            validate_fixed_record(data, self.RECORD_TYPE, self.RECORD_LENGTH)

            base = {
                "RecordSpec": self.decode_field(data[0:2]),
                "DataKubun": self.decode_field(data[2:3]),
                "MakeDate": self.decode_field(data[3:11]),
                "Year": self.decode_field(data[11:15]),
                "MonthDay": self.decode_field(data[15:19]),
                "JyoCD": self.decode_field(data[19:21]),
                "Kaiji": self.decode_field(data[21:23]),
                "Nichiji": self.decode_field(data[23:25]),
                "RaceNum": self.decode_field(data[25:27]),
                "HassoTime": self.decode_field(data[27:35]),
                "TorokuTosu": self.decode_field(data[35:37]),
                "SyussoTosu": self.decode_field(data[37:39]),
                "TanFlag": self.decode_field(data[39:40]),
                "FukuFlag": self.decode_field(data[40:41]),
                "WakurenFlag": self.decode_field(data[41:42]),
                "FukuChakubaraiKey": self.decode_field(data[42:43]),
            }

            # O1 has fixed arrays: 28 tan, 28 fuku, 36 wakuren, then 3 vote totals.
            tan_start = 43
            fuku_start = tan_start + 28 * 8
            wakuren_start = fuku_start + 28 * 12
            votes_start = wakuren_start + 36 * 9
            tan_vote = self.decode_field(data[votes_start:votes_start + 11])
            fuku_vote = self.decode_field(data[votes_start + 11:votes_start + 22])
            wakuren_vote = self.decode_field(data[votes_start + 22:votes_start + 33])
            base.update(
                {
                    "TanVote": tan_vote,
                    "FukuVote": fuku_vote,
                    "WakurenVote": wakuren_vote,
                }
            )

            rows_by_umaban: Dict[str, Dict[str, str]] = {}
            for i in range(28):
                pos = tan_start + i * 8
                item = data[pos:pos + 8]
                if len(item) < 8:
                    continue
                umaban = self.decode_field(item[0:2])
                odds = self.decode_field(item[2:6])
                ninki = self.decode_field(item[6:8])
                if not umaban.strip("0 "):
                    continue
                rows_by_umaban.setdefault(
                    umaban,
                    {**base, "Umaban": umaban, "FukuUmaban": umaban, "Kumi": "00"},
                )
                rows_by_umaban[umaban].update(
                    {"TanOdds": odds, "TanNinki": ninki, "TanVote": tan_vote}
                )

            for i in range(28):
                pos = fuku_start + i * 12
                item = data[pos:pos + 12]
                if len(item) < 12:
                    continue
                umaban = self.decode_field(item[0:2])
                low = self.decode_field(item[2:6])
                high = self.decode_field(item[6:10])
                ninki = self.decode_field(item[10:12])
                if not umaban.strip("0 "):
                    continue
                rows_by_umaban.setdefault(
                    umaban,
                    {**base, "Umaban": umaban, "FukuUmaban": umaban, "Kumi": "00"},
                )
                rows_by_umaban[umaban].update(
                    {
                        "FukuUmaban": umaban,
                        "FukuOddsLow": low,
                        "FukuOddsHigh": high,
                        "FukuNinki": ninki,
                        "FukuVote": fuku_vote,
                    }
                )

            rows = list(rows_by_umaban.values())
            for i in range(36):
                pos = wakuren_start + i * 9
                item = data[pos:pos + 9]
                if len(item) < 9:
                    continue
                kumi = self.decode_field(item[0:2])
                odds = self.decode_field(item[2:7])
                ninki = self.decode_field(item[7:9])
                if not kumi.strip("0 "):
                    continue
                rows.append(
                    {
                        **base,
                        "Umaban": "0",
                        "FukuUmaban": "",
                        "Kumi": kumi,
                        "WakurenOdds": odds,
                        "WakurenNinki": ninki,
                        "WakurenVote": wakuren_vote,
                    }
                )

            if rows:
                return rows
            # 単勝・複勝・枠連のいずれも提供されない snapshot（発売なし・
            # レース中止・削除）でも公式の票数合計は提供される。H1/H6 と同じ
            # sentinel 行で保持する。
            totals_only = dict(base)
            totals_only["Umaban"] = self.BRACKET_ROW_HORSE_NUMBER
            totals_only["FukuUmaban"] = ""
            totals_only["Kumi"] = self.TOTAL_COMBINATION
            return [totals_only]

        except Exception as e:
            self.logger.error(f"O1レコードパース中にエラー: {e}")
            return None
