#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
O2レコードパーサー: ８．オッズ2（馬連）

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class O2Parser:
    """
    O2レコードパーサー

    ８．オッズ2（馬連）
    レコード長: 66 bytes
    VBテーブル名: ODDS_UMAREN
    """

    RECORD_TYPE = "O2"
    RECORD_LENGTH = 66

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        O2レコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"O2レコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Year"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["MonthDay"] = self.decode_field(data[15:19])

            # 6. 競馬場コード (位置:20, 長さ:2)
            result["JyoCD"] = self.decode_field(data[19:21])

            # 7. 開催回[第N回] (位置:22, 長さ:2)
            result["Kaiji"] = self.decode_field(data[21:23])

            # 8. 開催日目[N日目] (位置:24, 長さ:2)
            result["Nichiji"] = self.decode_field(data[23:25])

            # 9. レース番号 (位置:26, 長さ:2)
            result["RaceNum"] = self.decode_field(data[25:27])

            # 10. 発表月日時分 (位置:28, 長さ:8)
            result["HassoTime"] = self.decode_field(data[27:35])

            # 11. 登録頭数 (位置:36, 長さ:2)
            result["TorokuTosu"] = self.decode_field(data[35:37])

            # 12. 出走頭数 (位置:38, 長さ:2)
            result["SyussoTosu"] = self.decode_field(data[37:39])

            # 13. 発売フラグ　馬連 (位置:40, 長さ:1)
            result["UmarenFlag"] = self.decode_field(data[39:40])

            # 14. <馬連オッズ> (位置:41, 長さ:0)
            # result["Field14"] = self.decode_field(data[40:40])

            # 15. 　　組番 (位置:41, 長さ:4)
            result["Kumi"] = self.decode_field(data[40:44])

            # 16. 　　オッズ (位置:45, 長さ:6)
            result["Odds"] = self.decode_field(data[44:50])

            # 17. 　　人気順 (位置:51, 長さ:3)
            result["Ninki"] = self.decode_field(data[50:53])

            # 18. 馬連票数合計 (位置:54, 長さ:11)
            result["Vote"] = self.decode_field(data[53:64])

            # 19. レコード区切 (位置:65, 長さ:2)
            # result["Field19"] = self.decode_field(data[64:66])

            return result

        except Exception as e:
            self.logger.error(f"O2レコードパース中にエラー: {e}")
            return None
