#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
O3レコードパーサー: ９．オッズ3（ワイド）

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, List, Optional

from src.parser import odds_domain
from src.parser.base import validate_fixed_record
from src.utils.logger import get_logger


class O3Parser(odds_domain.OddsCombinationValidationMixin):
    """
    O3レコードパーサー

    ９．オッズ3（ワイド）
    レコード長: 2654 bytes
    VBテーブル名: ODDS_WIDE
    """

    RECORD_TYPE = "O3"
    RECORD_LENGTH = 2654

    # 公式のデータ区分・発売フラグ・オッズ部の桁数（JV-Data 4.9.0.1）
    DATA_KUBUN_VALUES = odds_domain.DATA_KUBUN_VALUES
    SALE_FLAG_VALUES = odds_domain.SALE_FLAG_VALUES
    SALE_FLAG_FIELDS = ("WideFlag",)
    COMBINATION_WIDTH = 4
    ODDS_WIDTHS = (("OddsLow", 5), ("OddsHigh", 5))
    FAVOURITE_WIDTH = 3
    TOTAL_FIELDS = ("Vote",)
    # オッズ部の繰返し回数と1件のバイト数
    ENTRY_COUNT = 153
    ENTRY_WIDTH = 17
    # 組合せを持たない snapshot でも公式の票数合計を保持する sentinel
    TOTAL_COMBINATION = odds_domain.TOTAL_COMBINATION

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        return data.decode("cp932", errors="strict").strip()

    def parse(self, data: bytes) -> Optional[List[Dict[str, object]]]:
        """
        O3レコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            validate_fixed_record(data, self.RECORD_TYPE, self.RECORD_LENGTH)

            base = {
                "RecordSpec": self.decode_field(data[0:2]),
                "DataKubun": self.decode_field(data[2:3]),
                "MakeDate": self.decode_field(data[3:11]),
                "Year": self.decode_field(data[11:15]),
                "MonthDay": self.decode_field(data[15:19]),
                "JyoCD": self.decode_field(data[19:21]),
                "Kaiji": self.decode_field(data[21:23]),
                "Nichiji": self.decode_field(data[23:25]),
                "RaceNum": self.decode_field(data[25:27]),
                "HassoTime": self.decode_field(data[27:35]),
                "TorokuTosu": self.decode_field(data[35:37]),
                "SyussoTosu": self.decode_field(data[37:39]),
                "WideFlag": self.decode_field(data[39:40]),
            }
            vote = self.decode_field(data[-13:-2]) if len(data) >= 13 else ""
            base["Vote"] = vote
            rows = []
            for pos in range(40, max(40, len(data) - 13), 17):
                item = data[pos:pos + 17]
                if len(item) < 17:
                    continue
                kumi = self.decode_field(item[0:4])
                low = self.decode_field(item[4:9])
                high = self.decode_field(item[9:14])
                ninki = self.decode_field(item[14:17])
                if not kumi.strip("0 "):
                    continue
                rows.append(
                    {
                        **base,
                        "Kumi": kumi,
                        "OddsLow": low,
                        "OddsHigh": high,
                        "Ninki": ninki,
                        "Vote": vote,
                    }
                )

            if rows:
                return odds_domain.attach_snapshot_metadata(rows)
            # 組合せが1件も無い snapshot（発売なし・レース中止・削除）でも
            # 公式の票数合計は提供される。H1/H6 と同じ sentinel 行で保持する。
            totals_only = dict(base)
            totals_only["Kumi"] = self.TOTAL_COMBINATION
            totals_only["OddsLow"] = ""
            totals_only["OddsHigh"] = ""
            totals_only["Ninki"] = ""
            return odds_domain.attach_snapshot_metadata([totals_only])

        except Exception as e:
            self.logger.error(f"O3レコードパース中にエラー: {e}")
            return None
