#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
O4レコードパーサー: １０．オッズ4（馬単）

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, List, Optional

from src.parser import odds_domain
from src.parser.base import validate_fixed_record
from src.utils.logger import get_logger


class O4Parser(odds_domain.OddsCombinationValidationMixin):
    """
    O4レコードパーサー

    １０．オッズ4（馬単）
    レコード長: 4031 bytes
    VBテーブル名: ODDS_UMATAN
    """

    RECORD_TYPE = "O4"
    RECORD_LENGTH = 4031

    # 公式のデータ区分・発売フラグ・オッズ部の桁数（JV-Data 4.9.0.1）
    DATA_KUBUN_VALUES = odds_domain.DATA_KUBUN_VALUES
    SALE_FLAG_VALUES = odds_domain.SALE_FLAG_VALUES
    SALE_FLAG_FIELDS = ("UmatanFlag",)
    COMBINATION_WIDTH = 4
    ODDS_WIDTHS = (("Odds", 6),)
    FAVOURITE_WIDTH = 3
    TOTAL_FIELDS = ("Vote",)
    # オッズ部の繰返し回数と1件のバイト数
    ENTRY_COUNT = 306
    ENTRY_WIDTH = 13
    # 組合せを持たない snapshot でも公式の票数合計を保持する sentinel
    TOTAL_COMBINATION = odds_domain.TOTAL_COMBINATION

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        return data.decode("cp932", errors="strict").strip()

    def parse(self, data: bytes) -> Optional[List[Dict[str, object]]]:
        """
        O4レコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            validate_fixed_record(data, self.RECORD_TYPE, self.RECORD_LENGTH)

            base = {
                "RecordSpec": self.decode_field(data[0:2]),
                "DataKubun": self.decode_field(data[2:3]),
                "MakeDate": self.decode_field(data[3:11]),
                "Year": self.decode_field(data[11:15]),
                "MonthDay": self.decode_field(data[15:19]),
                "JyoCD": self.decode_field(data[19:21]),
                "Kaiji": self.decode_field(data[21:23]),
                "Nichiji": self.decode_field(data[23:25]),
                "RaceNum": self.decode_field(data[25:27]),
                "HassoTime": self.decode_field(data[27:35]),
                "TorokuTosu": self.decode_field(data[35:37]),
                "SyussoTosu": self.decode_field(data[37:39]),
                "UmatanFlag": self.decode_field(data[39:40]),
            }
            vote = self.decode_field(data[-13:-2]) if len(data) >= 13 else ""
            base["Vote"] = vote
            rows = []
            for pos in range(40, max(40, len(data) - 13), 13):
                item = data[pos:pos + 13]
                if len(item) < 13:
                    continue
                kumi = self.decode_field(item[0:4])
                odds = self.decode_field(item[4:10])
                ninki = self.decode_field(item[10:13])
                if not kumi.strip("0 "):
                    continue
                rows.append({**base, "Kumi": kumi, "Odds": odds, "Ninki": ninki, "Vote": vote})

            if rows:
                return odds_domain.attach_snapshot_metadata(rows)
            # 組合せが1件も無い snapshot（発売なし・レース中止・削除）でも
            # 公式の票数合計は提供される。H1/H6 と同じ sentinel 行で保持する。
            totals_only = dict(base)
            totals_only["Kumi"] = self.TOTAL_COMBINATION
            totals_only["Odds"] = ""
            totals_only["Ninki"] = ""
            return odds_domain.attach_snapshot_metadata([totals_only])

        except Exception as e:
            self.logger.error(f"O4レコードパース中にエラー: {e}")
            return None
