#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
O4レコードパーサー: １０．オッズ4（馬単）

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, List, Optional
from src.utils.logger import get_logger


class O4Parser:
    """
    O4レコードパーサー

    １０．オッズ4（馬単）
    レコード長: 66 bytes
    VBテーブル名: ODDS_UMATAN
    """

    RECORD_TYPE = "O4"
    RECORD_LENGTH = 66

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[List[Dict[str, str]]]:
        """
        O4レコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"O4レコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            base = {
                "RecordSpec": self.decode_field(data[0:2]),
                "DataKubun": self.decode_field(data[2:3]),
                "MakeDate": self.decode_field(data[3:11]),
                "Year": self.decode_field(data[11:15]),
                "MonthDay": self.decode_field(data[15:19]),
                "JyoCD": self.decode_field(data[19:21]),
                "Kaiji": self.decode_field(data[21:23]),
                "Nichiji": self.decode_field(data[23:25]),
                "RaceNum": self.decode_field(data[25:27]),
                "HassoTime": self.decode_field(data[27:35]),
                "TorokuTosu": self.decode_field(data[35:37]),
                "SyussoTosu": self.decode_field(data[37:39]),
                "UmatanFlag": self.decode_field(data[39:40]),
            }
            vote = self.decode_field(data[-13:-2]) if len(data) >= 13 else ""
            rows = []
            for pos in range(40, max(40, len(data) - 13), 13):
                item = data[pos:pos + 13]
                if len(item) < 13:
                    continue
                kumi = self.decode_field(item[0:4])
                odds = self.decode_field(item[4:10])
                ninki = self.decode_field(item[10:13])
                if not kumi.strip("0 ") or not odds.strip("0 "):
                    continue
                rows.append({**base, "Kumi": kumi, "Odds": odds, "Ninki": ninki, "Vote": vote})

            return rows

        except Exception as e:
            self.logger.error(f"O4レコードパース中にエラー: {e}")
            return None
