#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
RCレコードパーサー: ２１．レコードマスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class RCParser:
    """
    RCレコードパーサー

    ２１．レコードマスタ
    レコード長: 241 bytes
    VBテーブル名: RECORD
    """

    RECORD_TYPE = "RC"
    RECORD_LENGTH = 241

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        RCレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"RCレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. レコード識別区分 (位置:12, 長さ:1)
            result["RecInfoKubun"] = self.decode_field(data[11:12])

            # 5. 開催年 (位置:13, 長さ:4)
            result["Year"] = self.decode_field(data[12:16])

            # 6. 開催月日 (位置:17, 長さ:4)
            result["MonthDay"] = self.decode_field(data[16:20])

            # 7. 競馬場コード (位置:21, 長さ:2)
            result["JyoCD"] = self.decode_field(data[20:22])

            # 8. 開催回[第N回] (位置:23, 長さ:2)
            result["Kaiji"] = self.decode_field(data[22:24])

            # 9. 開催日目[N日目] (位置:25, 長さ:2)
            result["Nichiji"] = self.decode_field(data[24:26])

            # 10. レース番号 (位置:27, 長さ:2)
            result["RaceNum"] = self.decode_field(data[26:28])

            # 11. 特別競走番号 (位置:29, 長さ:4)
            result["TokuNum"] = self.decode_field(data[28:32])

            # 12. 競走名本題 (位置:33, 長さ:60)
            result["Hondai"] = self.decode_field(data[32:92])

            # 13. グレードコード (位置:93, 長さ:1)
            result["GradeCD"] = self.decode_field(data[92:93])

            # 14. 競走種別コード (位置:94, 長さ:2)
            result["SyubetuCD_TrackCD"] = self.decode_field(data[93:95])

            # 15. 距離 (位置:96, 長さ:4)
            result["Kyori"] = self.decode_field(data[95:99])

            # 16. トラックコード (位置:100, 長さ:2)
            result["RecKubun"] = self.decode_field(data[99:101])

            # 17. レコード区分 (位置:102, 長さ:1)
            result["RecTime"] = self.decode_field(data[101:102])

            # 18. レコードタイム (位置:103, 長さ:4)
            result["TenkoCD"] = self.decode_field(data[102:106])

            # 19. 天候コード (位置:107, 長さ:1)
            result["SibaBabaCD"] = self.decode_field(data[106:107])

            # 20. 芝馬場状態コード (位置:108, 長さ:1)
            result["DirtBabaCD"] = self.decode_field(data[107:108])

            # 21. ダート馬場状態コード (位置:109, 長さ:1)
            result["RecUmaKettoNum1"] = self.decode_field(data[108:109])

            # 22. <レコード保持馬情報> (位置:110, 長さ:0)
            result["RecUmaBamei1"] = self.decode_field(data[109:109])

            # 23. 　　血統登録番号 (位置:110, 長さ:10)
            result["RecUmaUmaKigoCD1"] = self.decode_field(data[109:119])

            # 24. 　　馬名 (位置:120, 長さ:36)
            result["RecUmaSexCD1"] = self.decode_field(data[119:155])

            # 25. 　　馬記号コード (位置:156, 長さ:2)
            result["RecUmaChokyosiCode1"] = self.decode_field(data[155:157])

            # 26. 　　性別コード (位置:158, 長さ:1)
            result["RecUmaChokyosiName1"] = self.decode_field(data[157:158])

            # 27. 　　調教師コード (位置:159, 長さ:5)
            result["RecUmaFutan1"] = self.decode_field(data[158:163])

            # 28. 　　調教師名 (位置:164, 長さ:34)
            result["RecUmaKisyuCode1"] = self.decode_field(data[163:197])

            # 29. 　　負担重量 (位置:198, 長さ:3)
            result["RecUmaKisyuName1"] = self.decode_field(data[197:200])

            # 30. 　　騎手コード (位置:201, 長さ:5)
            result["RecUmaKettoNum2"] = self.decode_field(data[200:205])

            # 31. 　　騎手名 (位置:206, 長さ:34)
            result["RecUmaBamei2"] = self.decode_field(data[205:239])

            # 32. レコード区切 (位置:240, 長さ:2)
            result["RecUmaUmaKigoCD2"] = self.decode_field(data[239:241])

            return result

        except Exception as e:
            self.logger.error(f"RCレコードパース中にエラー: {e}")
            return None
