#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
SKレコードパーサー: １９．産駒マスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from collections.abc import Mapping
from datetime import date

from src.parser import status_domain
from src.utils.logger import get_logger


class SKParser:
    """
    SKレコードパーサー

    １９．産駒マスタ
    レコード長: 208 bytes
    VBテーブル名: SANKU
    """

    RECORD_TYPE = "SK"
    RECORD_LENGTH = 208
    RECORD_DELIMITER_START = 206
    KEY_COLUMNS = ("KettoNum",)
    # 公式 4.9.0.1 産駒持込区分: 0:内国産 1:持込 2:輸入内国産扱い 3:輸入
    # (9:その他 は繁殖馬マスタ HN だけの値)
    SANKU_MOCHI_KUBUN_VALUES = frozenset({"0", "1", "2", "3"})
    PEDIGREE_FIELDS = (
        "FNum",
        "MNum",
        "FFNum",
        "FMNum",
        "MFNum",
        "MMNum",
        "FFFNum",
        "FFMNum",
        "FMFNum",
        "FMMNum",
        "MFFNum",
        "MFMNum",
        "MMFNum",
        "MMMNum",
    )
    BODY_FIELDS = (
        "BirthDate",
        "SexCD",
        "HinsyuCD",
        "KeiroCD",
        "SankuMochiKubun",
        "ImportYear",
        "BreederCode",
        "SanchiName",
        *PEDIGREE_FIELDS,
    )
    TEXT_FIELD_WIDTHS = {"SanchiName": 20}

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        return data.decode("cp932", errors="strict").strip()

    @staticmethod
    def _require_ascii_digits(field_name: str, value: object, width: int) -> str:
        if isinstance(value, str) and len(value) == width and value.isascii() and value.isdigit():
            return value
        raise ValueError(f"SK {field_name} must be exactly {width} ASCII digits")

    @classmethod
    def _require_date(cls, field_name: str, value: object) -> str:
        digits = cls._require_ascii_digits(field_name, value, 8)
        try:
            date(int(digits[:4]), int(digits[4:6]), int(digits[6:]))
        except ValueError as error:
            raise ValueError(f"SK {field_name} must be a real YYYYMMDD date") from error
        return digits

    @staticmethod
    def _require_cp932_text(field_name: str, value: object, width: int) -> None:
        if not isinstance(value, str):
            raise ValueError(f"SK {field_name} must be provider text")
        try:
            encoded = value.encode("cp932", errors="strict")
        except UnicodeEncodeError as error:
            raise ValueError(f"SK {field_name} is not CP932 encodable") from error
        if len(encoded) > width:
            raise ValueError(f"SK {field_name} exceeds its official {width}-byte span")

    @classmethod
    def validate_key_fields(cls, record: Mapping[str, object]) -> None:
        cls._require_date("MakeDate", record.get("MakeDate"))
        cls._require_ascii_digits("KettoNum", record.get("KettoNum"), 10)

    @classmethod
    def validate_current_fields(
        cls,
        record: Mapping[str, object],
        *,
        data_kubun: str | None = None,
    ) -> None:
        """Validate one current SK row before coercion or database mutation."""

        cls.validate_key_fields(record)
        status = data_kubun if data_kubun is not None else record.get("DataKubun")
        if status == "0":
            # An official delete command is defined by its exact identity. The
            # non-key provider bytes are deliberately not interpreted.
            return

        cls._require_date("BirthDate", record.get("BirthDate"))
        cls._require_ascii_digits("SexCD", record.get("SexCD"), 1)
        cls._require_ascii_digits("HinsyuCD", record.get("HinsyuCD"), 1)
        cls._require_ascii_digits("KeiroCD", record.get("KeiroCD"), 2)
        if record.get("SankuMochiKubun") not in cls.SANKU_MOCHI_KUBUN_VALUES:
            raise ValueError("SK SankuMochiKubun is not an official code")
        cls._require_ascii_digits("ImportYear", record.get("ImportYear"), 4)
        cls._require_ascii_digits("BreederCode", record.get("BreederCode"), 8)
        for field_name, width in cls.TEXT_FIELD_WIDTHS.items():
            cls._require_cp932_text(field_name, record.get(field_name), width)
        for field_name in cls.PEDIGREE_FIELDS:
            cls._require_ascii_digits(field_name, record.get(field_name), 10)

    @classmethod
    def _validate_envelope(cls, data: bytes) -> tuple[str, str]:
        if len(data) != cls.RECORD_LENGTH:
            raise ValueError(
                f"SK record length mismatch: expected={cls.RECORD_LENGTH}, actual={len(data)}"
            )
        if data[:2] != b"SK":
            raise ValueError(f"Record type mismatch: expected SK, got {data[:2]!r}")
        if data[cls.RECORD_DELIMITER_START : cls.RECORD_LENGTH] != b"\r\n":
            raise ValueError("SK record delimiter must be CRLF")
        data_kubun = data[2:3].decode("ascii", errors="strict")
        make_date = data[3:11].decode("ascii", errors="strict")
        cls._require_date("MakeDate", make_date)
        status_domain.validate_data_kubun("SK", data_kubun, make_date=make_date)
        return data_kubun, make_date

    def parse(self, data: bytes) -> dict[str, object] | None:
        """
        SKレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # 現行仕様の208バイト物理レコードだけを受理する。旧178バイト形を
            # 現行offsetで誤読せず、末尾区切りも厳密に検査する。
            data_kubun, _ = self._validate_envelope(data)

            if data_kubun != "0":
                # Live rows must remain losslessly decodable as CP932. Delete
                # rows intentionally decode only the header and key below.
                data.decode("cp932", errors="strict")

            # フィールド抽出
            result: dict[str, object] = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 血統登録番号 (位置:12, 長さ:10)
            result["KettoNum"] = self.decode_field(data[11:21])

            if data_kubun == "0":
                # 公式削除指示は identity だけで定義される。非 key 本文は
                # decode せず、header と exact key だけを検証する。
                for field_name in self.BODY_FIELDS:
                    result[field_name] = ""
                result["RecordDelimiter"] = None
                self.validate_current_fields(result, data_kubun=data_kubun)
                return result

            # 5. 生年月日 (位置:22, 長さ:8)
            result["BirthDate"] = self.decode_field(data[21:29])

            # 6. 性別コード (位置:30, 長さ:1)
            result["SexCD"] = self.decode_field(data[29:30])

            # 7. 品種コード (位置:31, 長さ:1)
            result["HinsyuCD"] = self.decode_field(data[30:31])

            # 8. 毛色コード (位置:32, 長さ:2)
            result["KeiroCD"] = self.decode_field(data[31:33])

            # 9. 産駒持込区分 (位置:34, 長さ:1)
            result["SankuMochiKubun"] = self.decode_field(data[33:34])

            # 10. 輸入年 (位置:35, 長さ:4)
            result["ImportYear"] = self.decode_field(data[34:38])

            # 11. 生産者コード (位置:39, 長さ:8)
            result["BreederCode"] = self.decode_field(data[38:46])

            # 12. 産地名 (位置:47, 長さ:20)
            result["SanchiName"] = self.decode_field(data[46:66])

            # 13. 3代血統 繁殖登録番号 (位置:67, 14回, 長さ:10)
            # fixture再構築ツールも同じsliceを読めるよう、生成コード形式で明示する。
            result["FNum"] = self.decode_field(data[66:76])
            result["MNum"] = self.decode_field(data[76:86])
            result["FFNum"] = self.decode_field(data[86:96])
            result["FMNum"] = self.decode_field(data[96:106])
            result["MFNum"] = self.decode_field(data[106:116])
            result["MMNum"] = self.decode_field(data[116:126])
            result["FFFNum"] = self.decode_field(data[126:136])
            result["FFMNum"] = self.decode_field(data[136:146])
            result["FMFNum"] = self.decode_field(data[146:156])
            result["FMMNum"] = self.decode_field(data[156:166])
            result["MFFNum"] = self.decode_field(data[166:176])
            result["MFMNum"] = self.decode_field(data[176:186])
            result["MMFNum"] = self.decode_field(data[186:196])
            result["MMMNum"] = self.decode_field(data[196:206])

            # 14. レコード区切 (位置:207, 長さ:2)
            result["RecordDelimiter"] = self.decode_field(data[206:208])

            self.validate_current_fields(result, data_kubun=data_kubun)

            return result

        except Exception as e:
            self.logger.error(f"SKレコードパース中にエラー: {e}")
            return None
