#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
UMレコードパーサー: １３．競走馬マスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class UMParser:
    """
    UMレコードパーサー

    １３．競走馬マスタ
    レコード長: 597 bytes
    VBテーブル名: UMA
    """

    RECORD_TYPE = "UM"
    RECORD_LENGTH = 597

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        UMレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"UMレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 血統登録番号 (位置:12, 長さ:10)
            result["DelKubun"] = self.decode_field(data[11:21])

            # 5. 競走馬抹消区分 (位置:22, 長さ:1)
            result["RegDate"] = self.decode_field(data[21:22])

            # 6. 競走馬登録年月日 (位置:23, 長さ:8)
            result["DelDate"] = self.decode_field(data[22:30])

            # 7. 競走馬抹消年月日 (位置:31, 長さ:8)
            result["BirthDate"] = self.decode_field(data[30:38])

            # 8. 生年月日 (位置:39, 長さ:8)
            result["Bamei"] = self.decode_field(data[38:46])

            # 9. 馬名 (位置:47, 長さ:36)
            result["BameiKana"] = self.decode_field(data[46:82])

            # 10. 馬名半角ｶﾅ (位置:83, 長さ:36)
            result["BameiEng"] = self.decode_field(data[82:118])

            # 11. 馬名欧字 (位置:119, 長さ:60)
            result["ZaikyuFlag"] = self.decode_field(data[118:178])

            # 12. JRA施設在きゅうフラグ (位置:179, 長さ:1)
            result["Reserved"] = self.decode_field(data[178:179])

            # 13. 予備 (位置:180, 長さ:19)
            result["UmaKigoCD"] = self.decode_field(data[179:198])

            # 14. 馬記号コード (位置:199, 長さ:2)
            result["SexCD"] = self.decode_field(data[198:200])

            # 15. 性別コード (位置:201, 長さ:1)
            result["HinsyuCD"] = self.decode_field(data[200:201])

            # 16. 品種コード (位置:202, 長さ:1)
            result["KeiroCD"] = self.decode_field(data[201:202])

            # 17. 毛色コード (位置:203, 長さ:2)
            result["Ketto3InfoHansyokuNum1"] = self.decode_field(data[202:204])

            # 18. <3代血統情報> (位置:205, 長さ:0)
            result["Ketto3InfoBamei1"] = self.decode_field(data[204:204])

            # 19. 　　繁殖登録番号 (位置:205, 長さ:10)
            result["Ketto3InfoHansyokuNum2"] = self.decode_field(data[204:214])

            # 20. 　　馬名 (位置:215, 長さ:36)
            result["Ketto3InfoBamei2"] = self.decode_field(data[214:250])

            # 21. 東西所属コード (位置:251, 長さ:1)
            result["Ketto3InfoHansyokuNum3"] = self.decode_field(data[250:251])

            # 22. 調教師コード (位置:252, 長さ:5)
            result["Ketto3InfoBamei3"] = self.decode_field(data[251:256])

            # 23. 調教師名略称 (位置:257, 長さ:8)
            result["Ketto3InfoHansyokuNum4"] = self.decode_field(data[256:264])

            # 24. 招待地域名 (位置:265, 長さ:20)
            result["Ketto3InfoBamei4"] = self.decode_field(data[264:284])

            # 25. 生産者コード (位置:285, 長さ:8)
            result["Ketto3InfoHansyokuNum5"] = self.decode_field(data[284:292])

            # 26. 生産者名(法人格無) (位置:293, 長さ:72)
            result["Ketto3InfoBamei5"] = self.decode_field(data[292:364])

            # 27. 産地名 (位置:365, 長さ:20)
            result["Ketto3InfoHansyokuNum6"] = self.decode_field(data[364:384])

            # 28. 馬主コード (位置:385, 長さ:6)
            result["Ketto3InfoBamei6"] = self.decode_field(data[384:390])

            # 29. 馬主名(法人格無) (位置:391, 長さ:64)
            result["Ketto3InfoHansyokuNum7"] = self.decode_field(data[390:454])

            # 30. 平地本賞金累計 (位置:455, 長さ:9)
            result["Ketto3InfoBamei7"] = self.decode_field(data[454:463])

            # 31. 障害本賞金累計 (位置:464, 長さ:9)
            result["Ketto3InfoHansyokuNum8"] = self.decode_field(data[463:472])

            # 32. 平地付加賞金累計 (位置:473, 長さ:9)
            result["Ketto3InfoBamei8"] = self.decode_field(data[472:481])

            # 33. 障害付加賞金累計 (位置:482, 長さ:9)
            result["Ketto3InfoHansyokuNum9"] = self.decode_field(data[481:490])

            # 34. 平地収得賞金累計 (位置:491, 長さ:9)
            result["Ketto3InfoBamei9"] = self.decode_field(data[490:499])

            # 35. 障害収得賞金累計 (位置:500, 長さ:9)
            result["Ketto3InfoHansyokuNum10"] = self.decode_field(data[499:508])

            # 36. 総合着回数 (位置:509, 長さ:3)
            result["Ketto3InfoBamei10"] = self.decode_field(data[508:511])

            # 37. 中央合計着回数 (位置:512, 長さ:3)
            result["Ketto3InfoHansyokuNum11"] = self.decode_field(data[511:514])

            # 38. <馬場別着回数> (位置:515, 長さ:0)
            result["Ketto3InfoBamei11"] = self.decode_field(data[514:514])

            # 39. 芝直・着回数 (位置:515, 長さ:3)
            result["Ketto3InfoHansyokuNum12"] = self.decode_field(data[514:517])

            # 40. 芝右・着回数 (位置:518, 長さ:3)
            result["Ketto3InfoBamei12"] = self.decode_field(data[517:520])

            # 41. 芝左・着回数 (位置:521, 長さ:3)
            result["Ketto3InfoHansyokuNum13"] = self.decode_field(data[520:523])

            # 42. ダ直・着回数 (位置:524, 長さ:3)
            result["Ketto3InfoBamei13"] = self.decode_field(data[523:526])

            # 43. ダ右・着回数 (位置:527, 長さ:3)
            result["Ketto3InfoHansyokuNum14"] = self.decode_field(data[526:529])

            # 44. ダ左・着回数 (位置:530, 長さ:3)
            result["Ketto3InfoBamei14"] = self.decode_field(data[529:532])

            # 45. 障害・着回数 (位置:533, 長さ:3)
            result["TozaiCD"] = self.decode_field(data[532:535])

            # 46. <馬場状態別着回数> (位置:536, 長さ:0)
            result["ChokyosiCode"] = self.decode_field(data[535:535])

            # 47. 芝良・着回数 (位置:536, 長さ:3)
            result["ChokyosiRyakusyo"] = self.decode_field(data[535:538])

            # 48. 芝稍・着回数 (位置:539, 長さ:3)
            result["Syotai"] = self.decode_field(data[538:541])

            # 49. 芝重・着回数 (位置:542, 長さ:3)
            result["BreederCode"] = self.decode_field(data[541:544])

            # 50. 芝不・着回数 (位置:545, 長さ:3)
            result["BreederName"] = self.decode_field(data[544:547])

            # 51. ダ良・着回数 (位置:548, 長さ:3)
            result["SanchiName"] = self.decode_field(data[547:550])

            # 52. ダ稍・着回数 (位置:551, 長さ:3)
            result["BanusiCode"] = self.decode_field(data[550:553])

            # 53. ダ重・着回数 (位置:554, 長さ:3)
            result["BanusiName"] = self.decode_field(data[553:556])

            # 54. ダ不・着回数 (位置:557, 長さ:3)
            result["RuikeiHonsyoHeiti"] = self.decode_field(data[556:559])

            # 55. 障良・着回数 (位置:560, 長さ:3)
            result["RuikeiHonsyoSyogai"] = self.decode_field(data[559:562])

            # 56. 障稍・着回数 (位置:563, 長さ:3)
            result["RuikeiFukaHeichi"] = self.decode_field(data[562:565])

            # 57. 障重・着回数 (位置:566, 長さ:3)
            result["RuikeiFukaSyogai"] = self.decode_field(data[565:568])

            # 58. 障不・着回数 (位置:569, 長さ:3)
            result["RuikeiSyutokuHeichi"] = self.decode_field(data[568:571])

            # 59. <距離別着回数> (位置:572, 長さ:0)
            result["RuikeiSyutokuSyogai"] = self.decode_field(data[571:571])

            # 60. 芝16下・着回数 (位置:572, 長さ:3)
            result["SogoChakukaisu1"] = self.decode_field(data[571:574])

            # 61. 芝22下・着回数 (位置:575, 長さ:3)
            result["SogoChakukaisu2"] = self.decode_field(data[574:577])

            # 62. 芝22超・着回数 (位置:578, 長さ:3)
            result["SogoChakukaisu3"] = self.decode_field(data[577:580])

            # 63. ダ16下・着回数 (位置:581, 長さ:3)
            result["SogoChakukaisu4"] = self.decode_field(data[580:583])

            # 64. ダ22下・着回数 (位置:584, 長さ:3)
            result["SogoChakukaisu5"] = self.decode_field(data[583:586])

            # 65. ダ22超・着回数 (位置:587, 長さ:3)
            result["SogoChakukaisu6"] = self.decode_field(data[586:589])

            # 66. 脚質傾向 (位置:590, 長さ:3)
            result["ChuoChakukaisu1"] = self.decode_field(data[589:592])

            # 67. 登録レース数 (位置:593, 長さ:3)
            result["ChuoChakukaisu2"] = self.decode_field(data[592:595])

            # 68. レコード区切 (位置:596, 長さ:2)
            result["ChuoChakukaisu3"] = self.decode_field(data[595:597])

            return result

        except Exception as e:
            self.logger.error(f"UMレコードパース中にエラー: {e}")
            return None
