#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
WFレコードパーサー: ３０．重勝式(WIN5)

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class WFParser:
    """
    WFレコードパーサー

    ３０．重勝式(WIN5)
    レコード長: 169 bytes
    VBテーブル名: JYUSYOSIKI
    """

    RECORD_TYPE = "WF"
    RECORD_LENGTH = 169

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        WFレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"WFレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["MakeDate"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["Year"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MonthDay"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Kumi"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["PayJyushosiki"] = self.decode_field(data[15:19])

            # 6. 予備 (位置:20, 長さ:2)
            result["TekichuHyo"] = self.decode_field(data[19:21])

            # 7. <重勝式対象レース情報> (位置:22, 長さ:8)
            result["Field7"] = self.decode_field(data[21:29])

            # 8. 競馬場コード (位置:30, 長さ:2)
            result["Field8"] = self.decode_field(data[29:31])

            # 9. 開催回[第N回] (位置:32, 長さ:2)
            result["Field9"] = self.decode_field(data[31:33])

            # 10. 開催日目[N日目] (位置:34, 長さ:2)
            result["Field10"] = self.decode_field(data[33:35])

            # 11. レース番号 (位置:36, 長さ:2)
            result["Field11"] = self.decode_field(data[35:37])

            # 12. 予備 (位置:38, 長さ:6)
            result["Field12"] = self.decode_field(data[37:43])

            # 13. 重勝式発売票数 (位置:44, 長さ:11)
            result["Field13"] = self.decode_field(data[43:54])

            # 14. <有効票数情報> (位置:55, 長さ:11)
            result["Field14"] = self.decode_field(data[54:65])

            # 15. 有効票数 (位置:66, 長さ:11)
            result["Field15"] = self.decode_field(data[65:76])

            # 16. 返還フラグ (位置:77, 長さ:1)
            result["Field16"] = self.decode_field(data[76:77])

            # 17. 不成立フラグ (位置:78, 長さ:1)
            result["Field17"] = self.decode_field(data[77:78])

            # 18. 的中無フラグ (位置:79, 長さ:1)
            result["Field18"] = self.decode_field(data[78:79])

            # 19. キャリーオーバー金額初期 (位置:80, 長さ:15)
            result["Field19"] = self.decode_field(data[79:94])

            # 20. キャリーオーバー金額残高 (位置:95, 長さ:15)
            result["Field20"] = self.decode_field(data[94:109])

            # 21. <重勝式払戻情報> (位置:110, 長さ:29)
            result["Field21"] = self.decode_field(data[109:138])

            # 22. 組番 (位置:139, 長さ:10)
            result["Field22"] = self.decode_field(data[138:148])

            # 23. 重勝式払戻金 (位置:149, 長さ:9)
            result["Field23"] = self.decode_field(data[148:157])

            # 24. 的中票数 (位置:158, 長さ:10)
            result["Field24"] = self.decode_field(data[157:167])

            # 25. レコード区切 (位置:168, 長さ:2)
            result["Field25"] = self.decode_field(data[167:169])

            return result

        except Exception as e:
            self.logger.error(f"WFレコードパース中にエラー: {e}")
            return None
