#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
WFレコードパーサー: ３０．重勝式(WIN5)

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class WFParser:
    """
    WFレコードパーサー

    ３０．重勝式(WIN5)
    レコード長: 169 bytes
    VBテーブル名: JYUSYOSIKI
    """

    RECORD_TYPE = "WF"
    RECORD_LENGTH = 169

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # Shift-JISでデコード、空白を除去
            return data.decode("shift-jis", errors="ignore").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        WFレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"WFレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Year"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["MonthDay"] = self.decode_field(data[15:19])

            # 6. 予備 (位置:20, 長さ:2)
            result["Yobi1"] = self.decode_field(data[19:21])

            # 7. 重勝式対象レース情報1 (位置:22, 長さ:8)
            result["RaceInfo1"] = self.decode_field(data[21:29])

            # 8. 重勝式対象レース情報2 (位置:30, 長さ:8)
            result["RaceInfo2"] = self.decode_field(data[29:37])

            # 9. 重勝式対象レース情報3 (位置:38, 長さ:8)
            result["RaceInfo3"] = self.decode_field(data[37:45])

            # 10. 重勝式対象レース情報4 (位置:46, 長さ:8)
            result["RaceInfo4"] = self.decode_field(data[45:53])

            # 11. 重勝式対象レース情報5 (位置:54, 長さ:8)
            result["RaceInfo5"] = self.decode_field(data[53:61])

            # 12. 予備 (位置:62, 長さ:6)
            result["Yobi2"] = self.decode_field(data[61:67])

            # 13. 重勝式発売票数 (位置:68, 長さ:11)
            result["HatubaiHyosu"] = self.decode_field(data[67:78])

            # 14. 有効票数 (位置:79, 長さ:11)
            result["YukoHyosu"] = self.decode_field(data[78:89])

            # 15. 返還フラグ (位置:90, 長さ:1)
            result["HenkanFlag"] = self.decode_field(data[89:90])

            # 16. 不成立フラグ (位置:91, 長さ:1)
            result["FuseirituFlag"] = self.decode_field(data[90:91])

            # 17. 的中無フラグ (位置:92, 長さ:1)
            result["TekichuNasiFlag"] = self.decode_field(data[91:92])

            # 18. キャリーオーバー金額初期 (位置:93, 長さ:15)
            result["CarryOverStart"] = self.decode_field(data[92:107])

            # 19. キャリーオーバー金額残高 (位置:108, 長さ:15)
            result["CarryOverBalance"] = self.decode_field(data[107:122])

            # 20. 組番 (位置:123, 長さ:10)
            result["Kumi"] = self.decode_field(data[122:132])

            # 21. 重勝式払戻金 (位置:133, 長さ:13)
            result["PayJyushosiki"] = self.decode_field(data[132:145])

            # 22. 的中票数 (位置:146, 長さ:11)
            result["TekichuHyosu"] = self.decode_field(data[145:156])

            # 23. 予備 (位置:157, 長さ:11)
            result["Yobi3"] = self.decode_field(data[156:167])

            # 24. レコード区切 (位置:168, 長さ:2)
            result["RecordDelimiter"] = self.decode_field(data[167:169])

            return result

        except Exception as e:
            self.logger.error(f"WFレコードパース中にエラー: {e}")
            return None
