"""Database schema manager for JLTSQL.

Optimized schema with appropriate data types for SQLite.
Auto-generated from JV-Data official specification.

Generated by: scripts/generate_simple_schema.py
Source: 公式JV-Data仕様書 Ver.4.9.0.1

Data Type Optimization:
- INTEGER: Year, Kaiji, Nichiji, RaceNum, Umaban, Kyori, counts, flags
- REAL: Odds, Time, Haron times, prize money
- TEXT: Codes (fixed-length), dates (YYYYMMDD), names, MonthDay (MMDD)

IMPORTANT - Duplicate Handling & Primary Keys:
==============================================

Current Status:
- ALL 58 tables now have PRIMARY KEY constraints defined
- INSERT OR REPLACE is used by default in the importer
- WITH primary keys, duplicate records will be UPDATED instead of created

Primary Keys Implemented:
-------------------------
Race-related Tables:
    NL_RA, RT_RA: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
    NL_SE, RT_SE: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
    NL_RC: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, RecInfoKubun)
    NL_TK: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
    NL_YS: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji)

Master Tables:
    NL_UM: PRIMARY KEY (KettoNum)  -- Horse registration number
    NL_SK: PRIMARY KEY (KettoNum)  -- Horse production
    NL_KS: PRIMARY KEY (KisyuCode)  -- Jockey code
    NL_CH: PRIMARY KEY (ChokyosiCode)  -- Trainer code
    NL_BN: PRIMARY KEY (BanusiCode)  -- Owner code
    NL_BR: PRIMARY KEY (BreederCode)  -- Breeder code
    NL_BT: PRIMARY KEY (HansyokuNum)  -- Breeding lineage
    NL_HN: PRIMARY KEY (HansyokuNum)  -- Breeding horse
    NL_CS: PRIMARY KEY (JyoCD, Kyori, TrackCD)  -- Course

Odds Tables:
    NL_O1, RT_O1: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
    NL_O2, RT_O2: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
    NL_O3, RT_O3: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
    NL_O4, RT_O4: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
    NL_O5, RT_O5: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
    NL_O6, RT_O6: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)

Payout Tables:
    NL_H1, RT_H1: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
    NL_H6, RT_H6: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, SanrentanKumi)
    NL_HR, RT_HR: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)

Additional Data Tables:
    NL_CK: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
    NL_HC: PRIMARY KEY (ChokyosiCode, Num, SetYear)
    NL_TM, RT_TM: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
    NL_WF: PRIMARY KEY (Year, MonthDay)

Change Information Tables:
    NL_CC, RT_CC: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
    NL_JC, RT_JC: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
    NL_TC, RT_TC: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
    NL_JG: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
    RT_RC: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)

Weather/Track Condition Tables:
    NL_WE, RT_WE: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HenkoID)
    NL_WH, RT_WH: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HappyoTime, HenkoID)

Pace/Data Mining Tables:
    NL_DM, RT_DM: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)

Sale/Auction Tables:
    NL_AV, RT_AV: PRIMARY KEY (KettoNum, SaleHostName, SaleName)
    NL_HS: PRIMARY KEY (KettoNum, SaleCode, FromDate)

Workout/Training Tables:
    NL_WC: PRIMARY KEY (ChokyoDate, ChokyoTime, KettoNum, Course)

Horse Name Table:
    NL_HY: PRIMARY KEY (Bamei)

Benefits with PRIMARY KEY constraints:
- INSERT OR REPLACE will update existing records instead of duplicating
- Safe to re-run imports multiple times
- Better data integrity and referential consistency
- Prevents duplicate records on re-import
- Optimized query performance on primary key columns
"""

from typing import Dict, List

from src.database.base import BaseDatabase
from src.utils.logger import get_logger

logger = get_logger(__name__)


SCHEMAS = {
    "NL_BN": """
        CREATE TABLE IF NOT EXISTS NL_BN (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            BanusiCode TEXT,
            BanusiName_Co TEXT,
            BanusiName TEXT,
            BanusiNameKana TEXT,
            BanusiNameEng TEXT,
            Fukusyoku TEXT,
            SetYear TEXT,
            HonSyokinTotal TEXT,
            FukaSyokin TEXT,
            ChakuKaisu TEXT,
            Reserved_386 TEXT,
            PRIMARY KEY (BanusiCode)
        )
    """,
    "NL_BR": """
        CREATE TABLE IF NOT EXISTS NL_BR (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            BreederCode TEXT,
            BreederName_Co TEXT,
            BreederName TEXT,
            BreederNameKana TEXT,
            BreederNameEng TEXT,
            Address TEXT,
            SetYear TEXT,
            HonSyokinTotal TEXT,
            FukaSyokin TEXT,
            ChakuKaisu TEXT,
            Reserved_454 TEXT,
            PRIMARY KEY (BreederCode)
        )
    """,
    "NL_BT": """
        CREATE TABLE IF NOT EXISTS NL_BT (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            HansyokuNum TEXT,
            KeitoId TEXT,
            KeitoName TEXT,
            KeitoEx TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (HansyokuNum)
        )
    """,

    "NL_AV": """
        CREATE TABLE IF NOT EXISTS NL_AV (
            RecordSpec TEXT,
            DataKubun TEXT,
            KettoNum TEXT,
            SaleHostName TEXT,
            SaleName TEXT,
            Price TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (KettoNum, SaleHostName, SaleName)
        )
    """,

    "NL_CC": """
        CREATE TABLE IF NOT EXISTS NL_CC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            HappyoTime TEXT,
            AtoKyori TEXT,
            AtoTruckCD TEXT,
            MaeKyori TEXT,
            MaeTruckCD TEXT,
            JiyuCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,

    "NL_CK": """
        CREATE TABLE IF NOT EXISTS NL_CK (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            KettoNum TEXT,
            Bamei TEXT,
            HeichiHonsyokinTotal TEXT,
            SyogaiHonsyokinTotal TEXT,
            HeichiFukasyokinTotal TEXT,
            SyogaiFukasyokinTotal TEXT,
            HeichiSyutokuTotal TEXT,
            SyogaiSyutokuTotal TEXT,
            TotalChakuCount TEXT,
            ChuoChakuCount TEXT,
            SibaChoChaku TEXT,
            SibaMigiChaku TEXT,
            SibaHidariChaku TEXT,
            DirtChoChaku TEXT,
            DirtMigiChaku TEXT,
            DirtHidariChaku TEXT,
            SyogaiChaku TEXT,
            SibaRyoChaku TEXT,
            SibaYayaChaku TEXT,
            SibaOmoChaku TEXT,
            SibaFuChaku TEXT,
            DirtRyoChaku TEXT,
            DirtYayaChaku TEXT,
            DirtOmoChaku TEXT,
            DirtFuChaku TEXT,
            SyogaiRyoChaku TEXT,
            SyogaiYayaChaku TEXT,
            SyogaiOmoChaku TEXT,
            SyogaiFuChaku TEXT,
            Siba1200IkaChaku TEXT,
            Siba1201_1400Chaku TEXT,
            Siba1401_1600Chaku TEXT,
            Siba1601_1800Chaku TEXT,
            Siba1801_2000Chaku TEXT,
            Siba2001_2200Chaku TEXT,
            Siba2201_2400Chaku TEXT,
            Siba2401_2800Chaku TEXT,
            Siba2801OverChaku TEXT,
            Dirt1200IkaChaku TEXT,
            Dirt1201_1400Chaku TEXT,
            Dirt1401_1600Chaku TEXT,
            Dirt1601_1800Chaku TEXT,
            Dirt1801_2000Chaku TEXT,
            Dirt2001_2200Chaku TEXT,
            Dirt2201_2400Chaku TEXT,
            Dirt2401_2800Chaku TEXT,
            Dirt2801OverChaku TEXT,
            SapporoSibaChaku TEXT,
            HakodateSibaChaku TEXT,
            FukushimaSibaChaku TEXT,
            NiigataSibaChaku TEXT,
            TokyoSibaChaku TEXT,
            NakayamaSibaChaku TEXT,
            ChukyoSibaChaku TEXT,
            KyotoSibaChaku TEXT,
            HanshinSibaChaku TEXT,
            KokuraSibaChaku TEXT,
            SapporoDirtChaku TEXT,
            HakodateDirtChaku TEXT,
            FukushimaDirtChaku TEXT,
            NiigataDirtChaku TEXT,
            TokyoDirtChaku TEXT,
            NakayamaDirtChaku TEXT,
            ChukyoDirtChaku TEXT,
            KyotoDirtChaku TEXT,
            HanshinDirtChaku TEXT,
            KokuraDirtChaku TEXT,
            SapporoSyogaiChaku TEXT,
            HakodateSyogaiChaku TEXT,
            FukushimaSyogaiChaku TEXT,
            NiigataSyogaiChaku TEXT,
            TokyoSyogaiChaku TEXT,
            NakayamaSyogaiChaku TEXT,
            ChukyoSyogaiChaku TEXT,
            KyotoSyogaiChaku TEXT,
            HanshinSyogaiChaku TEXT,
            KokuraSyogaiChaku TEXT,
            KyakusituKeiko TEXT,
            RegisteredRaceCount INTEGER,
            KisyuCode TEXT,
            KisyuName TEXT,
            KisyuResultsInfo TEXT,
            ChokyosiCode TEXT,
            ChokyosiName TEXT,
            ChokyosiResultsInfo TEXT,
            BanusiCode TEXT,
            BanusiName TEXT,
            BanusiName_Co TEXT,
            BanusiResultsInfo TEXT,
            BreederCode TEXT,
            BreederName TEXT,
            BreederName_Co TEXT,
            BreederResultsInfo TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
        )
    """,
    "NL_CH": """
        CREATE TABLE IF NOT EXISTS NL_CH (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            ChokyosiCode TEXT,
            DelKubun TEXT,
            IssueDate TEXT,
            DelDate TEXT,
            BirthDate TEXT,
            ChokyosiName TEXT,
            ChokyosiNameKana TEXT,
            ChokyosiRyakusyo TEXT,
            ChokyosiNameEng TEXT,
            SexCD TEXT,
            TozaiCD TEXT,
            Syotai TEXT,
            SaikinJyusyo1_id TEXT,
            SaikinJyusyo1_Hondai TEXT,
            SaikinJyusyo1_Ryakusyo10 TEXT,
            SaikinJyusyo1_Ryakusyo6 TEXT,
            SaikinJyusyo1_Ryakusyo3 TEXT,
            SaikinJyusyo1_GradeCD TEXT,
            SaikinJyusyo1_SyussoTosu TEXT,
            SaikinJyusyo1_KettoNum TEXT,
            SaikinJyusyo1_Bamei TEXT,
            SetYear TEXT,
            HonSyokinH TEXT,
            HonSyokinS TEXT,
            FukaSyokinH TEXT,
            FukaSyokinS TEXT,
            ChakuKaisuH TEXT,
            ChakuKaisuS TEXT,
            ChakuKaisu01H TEXT,
            ChakuKaisu01S TEXT,
            ChakuKaisu02H TEXT,
            ChakuKaisu02S TEXT,
            ChakuKaisu03H TEXT,
            ChakuKaisu03S TEXT,
            ChakuKaisu04H TEXT,
            ChakuKaisu04S TEXT,
            ChakuKaisu05H TEXT,
            ChakuKaisu05S TEXT,
            ChakuKaisu06H TEXT,
            ChakuKaisu06S TEXT,
            ChakuKaisu07H TEXT,
            ChakuKaisu07S TEXT,
            ChakuKaisu08H TEXT,
            ChakuKaisu08S TEXT,
            ChakuKaisu09H TEXT,
            ChakuKaisu09S TEXT,
            ChakuKaisu10H TEXT,
            ChakuKaisu10S TEXT,
            ChakuKaisuSiba1 TEXT,
            ChakuKaisuSiba2 TEXT,
            ChakuKaisuSiba3 TEXT,
            ChakuKaisuDirt1 TEXT,
            ChakuKaisuDirt2 TEXT,
            ChakuKaisuDirt3 TEXT,
            Reserved_591 TEXT,
            PRIMARY KEY (ChokyosiCode)
        )
    """,
    "NL_CS": """
        CREATE TABLE IF NOT EXISTS NL_CS (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            JyoCD TEXT,
            Kyori TEXT,
            TrackCD TEXT,
            KaishuDate TEXT,
            CourseEx TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (JyoCD, Kyori, TrackCD)
        )
    """,
    "NL_DM": """
        CREATE TABLE IF NOT EXISTS NL_DM (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            MakeHM TEXT,
            Umaban TEXT,
            DMTime TEXT,
            DMGosaP TEXT,
            DMGosaM TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "NL_H1": """
        CREATE TABLE IF NOT EXISTS NL_H1 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            HatubaiFlag1 TEXT,
            HatubaiFlag2 TEXT,
            HatubaiFlag3 TEXT,
            HatubaiFlag4 TEXT,
            HatubaiFlag5 TEXT,
            HatubaiFlag6 TEXT,
            HatubaiFlag7 TEXT,
            FukuChakuBaraiKey TEXT,
            HenkanUma1 TEXT,
            HenkanUma2 TEXT,
            HenkanUma3 TEXT,
            TanUma TEXT,
            TanHyo REAL,
            TanNinki INTEGER,
            FukuUma TEXT,
            FukuHyo REAL,
            FukuNinki INTEGER,
            WakuKumi TEXT,
            WakuHyo REAL,
            WakuNinki INTEGER,
            UmarenKumi TEXT,
            UmarenHyo REAL,
            UmarenNinki INTEGER,
            WideKumi TEXT,
            WideHyo REAL,
            WideNinki INTEGER,
            UmatanKumi TEXT,
            UmatanHyo REAL,
            UmatanNinki INTEGER,
            SanrenfukuKumi TEXT,
            SanrenfukuHyo REAL,
            SanrenfukuNinki INTEGER,
            TanHyoTotal REAL,
            FukuHyoTotal REAL,
            WakuHyoTotal REAL,
            UmarenHyoTotal REAL,
            WideHyoTotal REAL,
            UmatanHyoTotal REAL,
            SanrenfukuHyoTotal REAL,
            TanHenkanHyoTotal REAL,
            FukuHenkanHyoTotal REAL,
            WakuHenkanHyoTotal REAL,
            UmarenHenkanHyoTotal REAL,
            WideHenkanHyoTotal REAL,
            UmatanHenkanHyoTotal REAL,
            SanrenfukuHenkanHyoTotal REAL,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "NL_H6": """
        CREATE TABLE IF NOT EXISTS NL_H6 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            HatubaiFlag TEXT,
            HenkanUma TEXT,
            SanrentanKumi TEXT,
            SanrentanHyo REAL,
            SanrentanNinki INTEGER,
            SanrentanHyoTotal REAL,
            SanrentanHenkanHyoTotal REAL,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, SanrentanKumi)
        )
    """,
    "NL_HC": """
        CREATE TABLE IF NOT EXISTS NL_HC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            ChokyosiCode TEXT,
            Num TEXT,
            SetYear TEXT,
            HonSyokinHeichi TEXT,
            HonSyokinSyogai TEXT,
            FukaSyokinHeichi TEXT,
            FukaSyokinSyogai TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (ChokyosiCode, Num, SetYear)
        )
    """,
    "NL_HN": """
        CREATE TABLE IF NOT EXISTS NL_HN (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            HansyokuNum TEXT,
            reserved TEXT,
            KettoNum TEXT,
            DelKubun TEXT,
            Bamei TEXT,
            BameiKana TEXT,
            BameiEng TEXT,
            BirthYear TEXT,
            SexCD TEXT,
            HinsyuCD TEXT,
            KeiroCD TEXT,
            MochiKubun TEXT,
            ImportYear TEXT,
            SanchiName TEXT,
            FHansyokuNum TEXT,
            MHansyokuNum TEXT,
            Reserved_197 TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (HansyokuNum)
        )
    """,
    "NL_HR": """
        CREATE TABLE IF NOT EXISTS NL_HR (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            FuseirituFlag1 INTEGER,
            FuseirituFlag2 INTEGER,
            FuseirituFlag3 INTEGER,
            FuseirituFlag4 INTEGER,
            FuseirituFlag5 INTEGER,
            FuseirituFlag6 INTEGER,
            FuseirituFlag7 INTEGER,
            FuseirituFlag8 INTEGER,
            FuseirituFlag9 INTEGER,
            TokubaraiFlag1 INTEGER,
            TokubaraiFlag2 INTEGER,
            TokubaraiFlag3 INTEGER,
            TokubaraiFlag4 INTEGER,
            TokubaraiFlag5 INTEGER,
            TokubaraiFlag6 INTEGER,
            TokubaraiFlag7 INTEGER,
            TokubaraiFlag8 INTEGER,
            TokubaraiFlag9 INTEGER,
            HenkanFlag1 INTEGER,
            HenkanFlag2 INTEGER,
            HenkanFlag3 INTEGER,
            HenkanFlag4 INTEGER,
            HenkanFlag5 INTEGER,
            HenkanFlag6 INTEGER,
            HenkanFlag7 INTEGER,
            HenkanFlag8 INTEGER,
            HenkanFlag9 INTEGER,
            HenkanUma1 TEXT,
            HenkanUma2 TEXT,
            HenkanUma3 TEXT,
            HenkanUma4 TEXT,
            HenkanUma5 TEXT,
            HenkanUma6 TEXT,
            HenkanUma7 TEXT,
            HenkanUma8 TEXT,
            HenkanUma9 TEXT,
            HenkanUma10 TEXT,
            HenkanUma11 TEXT,
            HenkanUma12 TEXT,
            HenkanUma13 TEXT,
            HenkanUma14 TEXT,
            HenkanUma15 TEXT,
            HenkanUma16 TEXT,
            HenkanUma17 TEXT,
            HenkanUma18 TEXT,
            HenkanUma19 TEXT,
            HenkanUma20 TEXT,
            HenkanUma21 TEXT,
            HenkanUma22 TEXT,
            HenkanUma23 TEXT,
            HenkanUma24 TEXT,
            HenkanUma25 TEXT,
            HenkanUma26 TEXT,
            HenkanUma27 TEXT,
            HenkanUma28 TEXT,
            HenkanWaku1 TEXT,
            HenkanWaku2 TEXT,
            HenkanWaku3 TEXT,
            HenkanWaku4 TEXT,
            HenkanWaku5 TEXT,
            HenkanWaku6 TEXT,
            HenkanWaku7 TEXT,
            HenkanWaku8 TEXT,
            HenkanDoWaku1 TEXT,
            HenkanDoWaku2 TEXT,
            HenkanDoWaku3 TEXT,
            HenkanDoWaku4 TEXT,
            TanUmaban TEXT,
            TanPay BIGINT,
            TanNinki INTEGER,
            FukuUmaban TEXT,
            FukuPay BIGINT,
            FukuNinki INTEGER,
            WakuKumi TEXT,
            WakuPay BIGINT,
            WakuNinki INTEGER,
            UmarenKumi TEXT,
            UmarenPay BIGINT,
            UmarenNinki INTEGER,
            WideKumi TEXT,
            WidePay BIGINT,
            WideNinki INTEGER,
            Yobi1 TEXT,
            Yobi2 TEXT,
            Yobi3 TEXT,
            UmatanKumi TEXT,
            UmatanPay BIGINT,
            UmatanNinki INTEGER,
            SanrenfukuKumi TEXT,
            SanrenfukuPay BIGINT,
            SanrenfukuNinki INTEGER,
            SanrentanKumi TEXT,
            SanrentanPay BIGINT,
            SanrentanNinki INTEGER,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "NL_HS": """
        CREATE TABLE IF NOT EXISTS NL_HS (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            KettoNum TEXT,
            HansyokuFNum TEXT,
            HansyokuMNum TEXT,
            BirthYear TEXT,
            SaleCode TEXT,
            SaleHostName TEXT,
            SaleName TEXT,
            FromDate TEXT,
            ToDate TEXT,
            Barei TEXT,
            Price TEXT,
            Field15 TEXT,
            PRIMARY KEY (KettoNum, SaleCode, FromDate)
        )
    """,
    "NL_HY": """
        CREATE TABLE IF NOT EXISTS NL_HY (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Bamei TEXT,
            Field5 TEXT,
            Field6 TEXT,
            Field7 TEXT,
            PRIMARY KEY (Bamei)
        )
    """,
    "NL_JG": """
        CREATE TABLE IF NOT EXISTS NL_JG (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            KettoNum TEXT,
            Bamei TEXT,
            Num TEXT,
            SyussoKubun TEXT,
            JyogaiStateKubun TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
        )
    """,

    "NL_JC": """
        CREATE TABLE IF NOT EXISTS NL_JC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            HappyoTime TEXT,
            Umaban TEXT,
            Bamei TEXT,
            AtoFutan TEXT,
            AtoKisyuCode TEXT,
            AtoKisyuName TEXT,
            AtoMinaraiCD TEXT,
            MaeFutan TEXT,
            MaeKisyuCode TEXT,
            MaeKisyuName TEXT,
            MaeMinaraiCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "NL_KS": """
        CREATE TABLE IF NOT EXISTS NL_KS (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            KisyuCode TEXT,
            DelKubun TEXT,
            IssueDate TEXT,
            DelDate TEXT,
            BirthDate TEXT,
            KisyuName TEXT,
            reserved TEXT,
            KisyuNameKana TEXT,
            KisyuRyakusyo TEXT,
            KisyuNameEng TEXT,
            SexCD TEXT,
            SikakuCD TEXT,
            MinaraiCD TEXT,
            TozaiCD TEXT,
            Syotai TEXT,
            ChokyosiCode TEXT,
            ChokyosiRyakusyo TEXT,
            HatuKiJyo1Hatukijyoid TEXT,
            HatuKiJyo1SyussoTosu INTEGER,
            HatuKiJyo1KettoNum TEXT,
            HatuKiJyo1Bamei TEXT,
            HatuKiJyo1KakuteiJyuni INTEGER,
            HatuKiJyo1IJyoCD TEXT,
            HatuKiJyo2Hatukijyoid TEXT,
            HatuKiJyo2SyussoTosu INTEGER,
            HatuKiJyo2KettoNum TEXT,
            HatuKiJyo2Bamei TEXT,
            HatuKiJyo2KakuteiJyuni INTEGER,
            HatuKiJyo2IJyoCD TEXT,
            HatuSyori1Hatusyoriid TEXT,
            HatuSyori1SyussoTosu INTEGER,
            HatuSyori1KettoNum TEXT,
            HatuSyori1Bamei TEXT,
            HatuSyori2Hatusyoriid TEXT,
            HatuSyori2SyussoTosu INTEGER,
            HatuSyori2KettoNum TEXT,
            HatuSyori2Bamei TEXT,
            SaikinJyusyo1SaikinJyusyoid TEXT,
            SaikinJyusyo1Hondai TEXT,
            SaikinJyusyo1Ryakusyo10 TEXT,
            SaikinJyusyo1Ryakusyo6 TEXT,
            SaikinJyusyo1Ryakusyo3 TEXT,
            SaikinJyusyo1GradeCD TEXT,
            SaikinJyusyo1SyussoTosu INTEGER,
            SaikinJyusyo1KettoNum TEXT,
            SaikinJyusyo1Bamei TEXT,
            SaikinJyusyo2SaikinJyusyoid TEXT,
            SaikinJyusyo2Hondai TEXT,
            SaikinJyusyo2Ryakusyo10 TEXT,
            SaikinJyusyo2Ryakusyo6 TEXT,
            SaikinJyusyo2Ryakusyo3 TEXT,
            SaikinJyusyo2GradeCD TEXT,
            SaikinJyusyo2SyussoTosu INTEGER,
            SaikinJyusyo2KettoNum TEXT,
            SaikinJyusyo2Bamei TEXT,
            SaikinJyusyo3SaikinJyusyoid TEXT,
            SaikinJyusyo3Hondai TEXT,
            SaikinJyusyo3Ryakusyo10 TEXT,
            SaikinJyusyo3Ryakusyo6 TEXT,
            SaikinJyusyo3Ryakusyo3 TEXT,
            SaikinJyusyo3GradeCD TEXT,
            SaikinJyusyo3SyussoTosu INTEGER,
            SaikinJyusyo3KettoNum TEXT,
            SaikinJyusyo3Bamei TEXT,
            crlf TEXT,
            PRIMARY KEY (KisyuCode)
        )
    """,
    "NL_O1": """
        CREATE TABLE IF NOT EXISTS NL_O1 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            TanFlag TEXT,
            FukuFlag TEXT,
            WakurenFlag TEXT,
            FukuChakubaraiKey TEXT,
            Umaban INTEGER,
            TanOdds REAL,
            TanNinki INTEGER,
            FukuUmaban INTEGER,
            FukuOddsLow REAL,
            FukuOddsHigh REAL,
            FukuNinki INTEGER,
            Kumi TEXT,
            WakurenOdds REAL,
            WakurenNinki INTEGER,
            TanVote BIGINT,
            FukuVote BIGINT,
            WakurenVote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "NL_O2": """
        CREATE TABLE IF NOT EXISTS NL_O2 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmarenFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_O3": """
        CREATE TABLE IF NOT EXISTS NL_O3 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            WideFlag TEXT,
            Kumi TEXT,
            OddsLow REAL,
            OddsHigh REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_O4": """
        CREATE TABLE IF NOT EXISTS NL_O4 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmatanFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_O5": """
        CREATE TABLE IF NOT EXISTS NL_O5 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrenpukuFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_O6": """
        CREATE TABLE IF NOT EXISTS NL_O6 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrentanFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_RA": """
        CREATE TABLE IF NOT EXISTS NL_RA (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            YoubiCD TEXT,
            TokuNum TEXT,
            Hondai TEXT,
            Fukudai TEXT,
            Kakko TEXT,
            HondaiEng TEXT,
            FukudaiEng TEXT,
            KakkoEng TEXT,
            Ryakusyo10 TEXT,
            Ryakusyo6 TEXT,
            Ryakusyo3 TEXT,
            Kubun TEXT,
            Nkai TEXT,
            GradeCD TEXT,
            GradeCDBefore TEXT,
            SyubetuCD TEXT,
            KigoCD TEXT,
            JyuryoCD TEXT,
            JyokenCD1 TEXT,
            JyokenCD2 TEXT,
            JyokenCD3 TEXT,
            JyokenCD4 TEXT,
            JyokenCD5 TEXT,
            JyokenName TEXT,
            Kyori INTEGER,
            KyoriBefore INTEGER,
            TrackCD TEXT,
            TrackCDBefore TEXT,
            CourseKubunCD TEXT,
            CourseKubunCDBefore TEXT,
            Honsyokin1 REAL,
            Honsyokin2 REAL,
            Honsyokin3 REAL,
            Honsyokin4 REAL,
            HassoTime TEXT,
            HassoTimeBefore TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            NyusenTosu INTEGER,
            TenkoCD TEXT,
            SibaBabaCD TEXT,
            DirtBabaCD TEXT,
            LapTime TEXT,
            SyogaiMileTime TEXT,
            Haron3F REAL,
            Haron4F REAL,
            Haron3L REAL,
            Haron4L REAL,
            Corner TEXT,
            Syukaisu INTEGER,
            TsukaJyuni TEXT,
            RecordUpKubun TEXT,
            Crlf TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "NL_RC": """
        CREATE TABLE IF NOT EXISTS NL_RC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            RecInfoKubun TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            TokuNum TEXT,
            Hondai TEXT,
            GradeCD TEXT,
            SyubetuCD_TrackCD TEXT,
            Kyori TEXT,
            RecKubun TEXT,
            RecTime TEXT,
            TenkoCD TEXT,
            SibaBabaCD TEXT,
            DirtBabaCD TEXT,
            RecUmaKettoNum1 TEXT,
            RecUmaBamei1 TEXT,
            RecUmaUmaKigoCD1 TEXT,
            RecUmaSexCD1 TEXT,
            RecUmaChokyosiCode1 TEXT,
            RecUmaChokyosiName1 TEXT,
            RecUmaFutan1 TEXT,
            RecUmaKisyuCode1 TEXT,
            RecUmaKisyuName1 TEXT,
            RecUmaKettoNum2 TEXT,
            RecUmaBamei2 TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, RecInfoKubun)
        )
    """,
    "NL_SE": """
        CREATE TABLE IF NOT EXISTS NL_SE (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            Wakuban INTEGER,
            Umaban INTEGER,
            KettoNum TEXT,
            Bamei TEXT,
            UmaKigoCD TEXT,
            SexCD TEXT,
            HinsyuCD TEXT,
            KeiroCD TEXT,
            Barei INTEGER,
            TozaiCD TEXT,
            ChokyosiCode TEXT,
            ChokyosiRyakusyo TEXT,
            BanusiCode TEXT,
            BanusiName TEXT,
            Fukusyoku TEXT,
            Reserved_229 TEXT,
            Futan REAL,
            FutanBefore REAL,
            Blinker TEXT,
            Reserved_296 TEXT,
            KisyuCode TEXT,
            KisyuCodeBefore TEXT,
            KisyuRyakusyo TEXT,
            KisyuRyakusyoBefore TEXT,
            MinaraiCD TEXT,
            MinaraiCDBefore TEXT,
            BaTaijyu REAL,
            ZogenFugo TEXT,
            ZogenSa REAL,
            IJyoCD TEXT,
            NyusenJyuni INTEGER,
            KakuteiJyuni INTEGER,
            DochakuKubun TEXT,
            DochakuTosu INTEGER,
            Time REAL,
            ChakusaCD TEXT,
            ChakusaCDP TEXT,
            ChakusaCDPP TEXT,
            Jyuni1c INTEGER,
            Jyuni2c INTEGER,
            Jyuni3c INTEGER,
            Jyuni4c INTEGER,
            Odds REAL,
            Ninki INTEGER,
            Honsyokin REAL,
            Fukasyokin REAL,
            Reserved_382 TEXT,
            Reserved_385 TEXT,
            HaronTimeL4 REAL,
            HaronTimeL3 REAL,
            KettoNum1 TEXT,
            Bamei1 TEXT,
            TimeDiff REAL,
            RecordUpKubun TEXT,
            DMKubun TEXT,
            DMTime REAL,
            DMGosaP REAL,
            DMGosaM REAL,
            DMJyuni INTEGER,
            KyakusituKubun TEXT,
            Reserved_462 TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "NL_SK": """
        CREATE TABLE IF NOT EXISTS NL_SK (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            KettoNum TEXT,
            BirthDate TEXT,
            SexCD TEXT,
            HinsyuCD TEXT,
            KeiroCD TEXT,
            SankuMochiKubun TEXT,
            ImportYear INTEGER,
            BreederCode TEXT,
            SanchiName TEXT,
            FNum TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (KettoNum)
        )
    """,

    "NL_TC": """
        CREATE TABLE IF NOT EXISTS NL_TC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            HappyoTime TEXT,
            AtoJi TEXT,
            AtoFun TEXT,
            MaeJi TEXT,
            MaeFun TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "NL_TK": """
        CREATE TABLE IF NOT EXISTS NL_TK (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            YoubiCD TEXT,
            TokuNum TEXT,
            Hondai TEXT,
            Fukudai TEXT,
            Kakko TEXT,
            HondaiEng TEXT,
            FukudaiEng TEXT,
            KakkoEng TEXT,
            RaceRyakusyo10 TEXT,
            RaceRyakusyo6 TEXT,
            RaceRyakusyo3 TEXT,
            RaceMeiKubun TEXT,
            JyusyoKaiji TEXT,
            GradeCD TEXT,
            SyubetuCD TEXT,
            KigoCD TEXT,
            JyuryoCD TEXT,
            JyokenCD2 TEXT,
            JyokenCD3 TEXT,
            JyokenCD4 TEXT,
            JyokenCD5 TEXT,
            JyokenCDYoung TEXT,
            Kyori TEXT,
            TrackCD TEXT,
            CourseKubun TEXT,
            HandeHappyoDate TEXT,
            TorokuTosu TEXT,
            RenbanNum TEXT,
            KettoNum TEXT,
            Bamei TEXT,
            UmaKigoCD TEXT,
            SexCD TEXT,
            TozaiCD TEXT,
            ChokyosiCode TEXT,
            ChokyosiRyakusyo TEXT,
            Futan TEXT,
            Koryu TEXT,
            RecordBreak TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
        )
    """,
    "NL_TM": """
        CREATE TABLE IF NOT EXISTS NL_TM (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            MakeHM TEXT,
            Umaban INTEGER,
            TMScore INTEGER,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "NL_UM": """
        CREATE TABLE IF NOT EXISTS NL_UM (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            KettoNum TEXT,
            DelKubun TEXT,
            RegDate TEXT,
            DelDate TEXT,
            BirthDate TEXT,
            Bamei TEXT,
            BameiKana TEXT,
            BameiEng TEXT,
            ZaikyuFlag INTEGER,
            Reserved TEXT,
            UmaKigoCD TEXT,
            SexCD TEXT,
            HinsyuCD TEXT,
            KeiroCD TEXT,
            Ketto3InfoHansyokuNum1 TEXT,
            Ketto3InfoBamei1 TEXT,
            Ketto3InfoHansyokuNum2 TEXT,
            Ketto3InfoBamei2 TEXT,
            Ketto3InfoHansyokuNum3 TEXT,
            Ketto3InfoBamei3 TEXT,
            Ketto3InfoHansyokuNum4 TEXT,
            Ketto3InfoBamei4 TEXT,
            Ketto3InfoHansyokuNum5 TEXT,
            Ketto3InfoBamei5 TEXT,
            Ketto3InfoHansyokuNum6 TEXT,
            Ketto3InfoBamei6 TEXT,
            Ketto3InfoHansyokuNum7 TEXT,
            Ketto3InfoBamei7 TEXT,
            Ketto3InfoHansyokuNum8 TEXT,
            Ketto3InfoBamei8 TEXT,
            Ketto3InfoHansyokuNum9 TEXT,
            Ketto3InfoBamei9 TEXT,
            Ketto3InfoHansyokuNum10 TEXT,
            Ketto3InfoBamei10 TEXT,
            Ketto3InfoHansyokuNum11 TEXT,
            Ketto3InfoBamei11 TEXT,
            Ketto3InfoHansyokuNum12 TEXT,
            Ketto3InfoBamei12 TEXT,
            Ketto3InfoHansyokuNum13 TEXT,
            Ketto3InfoBamei13 TEXT,
            Ketto3InfoHansyokuNum14 TEXT,
            Ketto3InfoBamei14 TEXT,
            TozaiCD TEXT,
            ChokyosiCode TEXT,
            ChokyosiRyakusyo TEXT,
            Syotai TEXT,
            BreederCode TEXT,
            BreederName TEXT,
            SanchiName TEXT,
            BanusiCode TEXT,
            BanusiName TEXT,
            RuikeiHonsyoHeiti REAL,
            RuikeiHonsyoSyogai REAL,
            RuikeiFukaHeichi REAL,
            RuikeiFukaSyogai REAL,
            RuikeiSyutokuHeichi REAL,
            RuikeiSyutokuSyogai REAL,
            Reserved_1107 TEXT,
            PRIMARY KEY (KettoNum)
        )
    """,

    "NL_WC": """
        CREATE TABLE IF NOT EXISTS NL_WC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            TresenKubun TEXT,
            ChokyoDate TEXT,
            ChokyoTime TEXT,
            KettoNum TEXT,
            Course TEXT,
            BabaMawari TEXT,
            reserved TEXT,
            HaronTime10Total TEXT,
            LapTime_2000M_1800M TEXT,
            HaronTime9Total TEXT,
            LapTime_1800M_1600M TEXT,
            HaronTime8Total TEXT,
            LapTime_1600M_1400M TEXT,
            HaronTime7Total TEXT,
            LapTime_1400M_1200M TEXT,
            HaronTime6Total TEXT,
            LapTime_1200M_1000M TEXT,
            HaronTime5Total TEXT,
            LapTime_1000M_800M TEXT,
            HaronTime4Total TEXT,
            LapTime_800M_600M TEXT,
            HaronTime3Total TEXT,
            LapTime_600M_400M TEXT,
            HaronTime2Total TEXT,
            LapTime_400M_200M TEXT,
            LapTime_200M_0M TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (ChokyoDate, ChokyoTime, KettoNum, Course)
        )
    """,

    "NL_WE": """
        CREATE TABLE IF NOT EXISTS NL_WE (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            HappyoTime TEXT,
            HenkoID TEXT,
            TenkoState TEXT,
            SibaBabaState TEXT,
            DirtBabaState TEXT,
            TenkoState2 TEXT,
            SibaBabaState2 TEXT,
            DirtBabaState2 TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HenkoID)
        )
    """,

    "NL_WH": """
        CREATE TABLE IF NOT EXISTS NL_WH (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            HappyoTime TEXT,
            HenkoID TEXT,
            AtoTenkoCD TEXT,
            AtoSibaBabaCD TEXT,
            AtoDirtBabaCD TEXT,
            MaeTenkoCD TEXT,
            MaeSibaBabaCD TEXT,
            MaeDirtBabaCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HappyoTime, HenkoID)
        )
    """,
    "NL_WF": """
        CREATE TABLE IF NOT EXISTS NL_WF (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            Yobi1 TEXT,
            RaceInfo1 TEXT,
            RaceInfo2 TEXT,
            RaceInfo3 TEXT,
            RaceInfo4 TEXT,
            RaceInfo5 TEXT,
            Yobi2 TEXT,
            HatubaiHyosu BIGINT,
            YukoHyosu BIGINT,
            HenkanFlag TEXT,
            FuseirituFlag TEXT,
            TekichuNasiFlag TEXT,
            CarryOverStart BIGINT,
            CarryOverBalance BIGINT,
            Kumi TEXT,
            PayJyushosiki BIGINT,
            TekichuHyosu BIGINT,
            Yobi3 TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay)
        )
    """,
    "NL_YS": """
        CREATE TABLE IF NOT EXISTS NL_YS (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            YoubiCD TEXT,
            Jyusyo1TokuNum INTEGER,
            Jyusyo1Hondai TEXT,
            Jyusyo1Ryakusyo10 TEXT,
            Jyusyo1Ryakusyo6 TEXT,
            Jyusyo1Ryakusyo3 TEXT,
            Jyusyo1Nkai INTEGER,
            Jyusyo1GradeCD TEXT,
            Jyusyo1SyubetuCD TEXT,
            Jyusyo1KigoCD TEXT,
            Jyusyo1JyuryoCD TEXT,
            Jyusyo1Kyori INTEGER,
            Jyusyo1TrackCD TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji)
        )
    """,

    # RT_ tables (Real-time data)
    "RT_AV": """
        CREATE TABLE IF NOT EXISTS RT_AV (
            RecordSpec TEXT,
            DataKubun TEXT,
            KettoNum TEXT,
            SaleHostName TEXT,
            SaleName TEXT,
            Price TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (KettoNum, SaleHostName, SaleName)
        )
    """,
    "RT_CC": """
        CREATE TABLE IF NOT EXISTS RT_CC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            HappyoTime TEXT,
            AtoKyori TEXT,
            AtoTruckCD TEXT,
            MaeKyori TEXT,
            MaeTruckCD TEXT,
            JiyuCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "RT_DM": """
        CREATE TABLE IF NOT EXISTS RT_DM (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            MakeHM TEXT,
            Umaban TEXT,
            DMTime TEXT,
            DMGosaP TEXT,
            DMGosaM TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_H1": """
        CREATE TABLE IF NOT EXISTS RT_H1 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            HatubaiFlag1 TEXT,
            HatubaiFlag2 TEXT,
            HatubaiFlag3 TEXT,
            HatubaiFlag4 TEXT,
            HatubaiFlag5 TEXT,
            HatubaiFlag6 TEXT,
            HatubaiFlag7 TEXT,
            FukuChakuBaraiKey TEXT,
            HenkanUma1 TEXT,
            HenkanUma2 TEXT,
            HenkanUma3 TEXT,
            TanUma TEXT,
            TanHyo REAL,
            TanNinki INTEGER,
            FukuUma TEXT,
            FukuHyo REAL,
            FukuNinki INTEGER,
            WakuKumi TEXT,
            WakuHyo REAL,
            WakuNinki INTEGER,
            UmarenKumi TEXT,
            UmarenHyo REAL,
            UmarenNinki INTEGER,
            WideKumi TEXT,
            WideHyo REAL,
            WideNinki INTEGER,
            UmatanKumi TEXT,
            UmatanHyo REAL,
            UmatanNinki INTEGER,
            SanrenfukuKumi TEXT,
            SanrenfukuHyo REAL,
            SanrenfukuNinki INTEGER,
            TanHyoTotal REAL,
            FukuHyoTotal REAL,
            WakuHyoTotal REAL,
            UmarenHyoTotal REAL,
            WideHyoTotal REAL,
            UmatanHyoTotal REAL,
            SanrenfukuHyoTotal REAL,
            TanHenkanHyoTotal REAL,
            FukuHenkanHyoTotal REAL,
            WakuHenkanHyoTotal REAL,
            UmarenHenkanHyoTotal REAL,
            WideHenkanHyoTotal REAL,
            UmatanHenkanHyoTotal REAL,
            SanrenfukuHenkanHyoTotal REAL,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "RT_H6": """
        CREATE TABLE IF NOT EXISTS RT_H6 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            HatubaiFlag TEXT,
            HenkanUma TEXT,
            SanrentanKumi TEXT,
            SanrentanHyo REAL,
            SanrentanNinki INTEGER,
            SanrentanHyoTotal REAL,
            SanrentanHenkanHyoTotal REAL,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, SanrentanKumi)
        )
    """,
    "RT_HR": """
        CREATE TABLE IF NOT EXISTS RT_HR (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            FuseirituFlag1 INTEGER,
            FuseirituFlag2 INTEGER,
            FuseirituFlag3 INTEGER,
            FuseirituFlag4 INTEGER,
            FuseirituFlag5 INTEGER,
            FuseirituFlag6 INTEGER,
            FuseirituFlag7 INTEGER,
            FuseirituFlag8 INTEGER,
            FuseirituFlag9 INTEGER,
            TokubaraiFlag1 INTEGER,
            TokubaraiFlag2 INTEGER,
            TokubaraiFlag3 INTEGER,
            TokubaraiFlag4 INTEGER,
            TokubaraiFlag5 INTEGER,
            TokubaraiFlag6 INTEGER,
            TokubaraiFlag7 INTEGER,
            TokubaraiFlag8 INTEGER,
            TokubaraiFlag9 INTEGER,
            HenkanFlag1 INTEGER,
            HenkanFlag2 INTEGER,
            HenkanFlag3 INTEGER,
            HenkanFlag4 INTEGER,
            HenkanFlag5 INTEGER,
            HenkanFlag6 INTEGER,
            HenkanFlag7 INTEGER,
            HenkanFlag8 INTEGER,
            HenkanFlag9 INTEGER,
            HenkanUma1 TEXT,
            HenkanUma2 TEXT,
            HenkanUma3 TEXT,
            HenkanUma4 TEXT,
            HenkanUma5 TEXT,
            HenkanUma6 TEXT,
            HenkanUma7 TEXT,
            HenkanUma8 TEXT,
            HenkanUma9 TEXT,
            HenkanUma10 TEXT,
            HenkanUma11 TEXT,
            HenkanUma12 TEXT,
            HenkanUma13 TEXT,
            HenkanUma14 TEXT,
            HenkanUma15 TEXT,
            HenkanUma16 TEXT,
            HenkanUma17 TEXT,
            HenkanUma18 TEXT,
            HenkanUma19 TEXT,
            HenkanUma20 TEXT,
            HenkanUma21 TEXT,
            HenkanUma22 TEXT,
            HenkanUma23 TEXT,
            HenkanUma24 TEXT,
            HenkanUma25 TEXT,
            HenkanUma26 TEXT,
            HenkanUma27 TEXT,
            HenkanUma28 TEXT,
            HenkanWaku1 TEXT,
            HenkanWaku2 TEXT,
            HenkanWaku3 TEXT,
            HenkanWaku4 TEXT,
            HenkanWaku5 TEXT,
            HenkanWaku6 TEXT,
            HenkanWaku7 TEXT,
            HenkanWaku8 TEXT,
            HenkanDoWaku1 TEXT,
            HenkanDoWaku2 TEXT,
            HenkanDoWaku3 TEXT,
            HenkanDoWaku4 TEXT,
            TanUmaban TEXT,
            TanPay BIGINT,
            TanNinki INTEGER,
            FukuUmaban TEXT,
            FukuPay BIGINT,
            FukuNinki INTEGER,
            WakuKumi TEXT,
            WakuPay BIGINT,
            WakuNinki INTEGER,
            UmarenKumi TEXT,
            UmarenPay BIGINT,
            UmarenNinki INTEGER,
            WideKumi TEXT,
            WidePay BIGINT,
            WideNinki INTEGER,
            Yobi1 TEXT,
            Yobi2 TEXT,
            Yobi3 TEXT,
            UmatanKumi TEXT,
            UmatanPay BIGINT,
            UmatanNinki INTEGER,
            SanrenfukuKumi TEXT,
            SanrenfukuPay BIGINT,
            SanrenfukuNinki INTEGER,
            SanrentanKumi TEXT,
            SanrentanPay BIGINT,
            SanrentanNinki INTEGER,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "RT_JC": """
        CREATE TABLE IF NOT EXISTS RT_JC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            HappyoTime TEXT,
            Umaban TEXT,
            Bamei TEXT,
            AtoFutan TEXT,
            AtoKisyuCode TEXT,
            AtoKisyuName TEXT,
            AtoMinaraiCD TEXT,
            MaeFutan TEXT,
            MaeKisyuCode TEXT,
            MaeKisyuName TEXT,
            MaeMinaraiCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_O1": """
        CREATE TABLE IF NOT EXISTS RT_O1 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            TanFlag TEXT,
            FukuFlag TEXT,
            WakurenFlag TEXT,
            FukuChakubaraiKey TEXT,
            Umaban INTEGER,
            TanOdds REAL,
            TanNinki INTEGER,
            FukuUmaban INTEGER,
            FukuOddsLow REAL,
            FukuOddsHigh REAL,
            FukuNinki INTEGER,
            Kumi TEXT,
            WakurenOdds REAL,
            WakurenNinki INTEGER,
            TanVote BIGINT,
            FukuVote BIGINT,
            WakurenVote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_O2": """
        CREATE TABLE IF NOT EXISTS RT_O2 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmarenFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "RT_O3": """
        CREATE TABLE IF NOT EXISTS RT_O3 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            WideFlag TEXT,
            Kumi TEXT,
            OddsLow REAL,
            OddsHigh REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "RT_O4": """
        CREATE TABLE IF NOT EXISTS RT_O4 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmatanFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "RT_O5": """
        CREATE TABLE IF NOT EXISTS RT_O5 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrenpukuFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "RT_O6": """
        CREATE TABLE IF NOT EXISTS RT_O6 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrentanFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "RT_RA": """
        CREATE TABLE IF NOT EXISTS RT_RA (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            YoubiCD TEXT,
            TokuNum TEXT,
            Hondai TEXT,
            Fukudai TEXT,
            Kakko TEXT,
            HondaiEng TEXT,
            FukudaiEng TEXT,
            KakkoEng TEXT,
            Ryakusyo10 TEXT,
            Ryakusyo6 TEXT,
            Ryakusyo3 TEXT,
            Kubun TEXT,
            Nkai TEXT,
            GradeCD TEXT,
            GradeCDBefore TEXT,
            SyubetuCD TEXT,
            KigoCD TEXT,
            JyuryoCD TEXT,
            JyokenCD1 TEXT,
            JyokenCD2 TEXT,
            JyokenCD3 TEXT,
            JyokenCD4 TEXT,
            JyokenCD5 TEXT,
            JyokenName TEXT,
            Kyori INTEGER,
            KyoriBefore INTEGER,
            TrackCD TEXT,
            TrackCDBefore TEXT,
            CourseKubunCD TEXT,
            CourseKubunCDBefore TEXT,
            Honsyokin1 REAL,
            Honsyokin2 REAL,
            Honsyokin3 REAL,
            Honsyokin4 REAL,
            HassoTime TEXT,
            HassoTimeBefore TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            NyusenTosu INTEGER,
            TenkoCD TEXT,
            SibaBabaCD TEXT,
            DirtBabaCD TEXT,
            LapTime TEXT,
            SyogaiMileTime TEXT,
            Haron3F REAL,
            Haron4F REAL,
            Haron3L REAL,
            Haron4L REAL,
            Corner TEXT,
            Syukaisu INTEGER,
            TsukaJyuni TEXT,
            RecordUpKubun TEXT,
            Crlf TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "RT_SE": """
        CREATE TABLE IF NOT EXISTS RT_SE (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            Wakuban INTEGER,
            Umaban INTEGER,
            KettoNum TEXT,
            Bamei TEXT,
            UmaKigoCD TEXT,
            SexCD TEXT,
            HinsyuCD TEXT,
            KeiroCD TEXT,
            Barei INTEGER,
            TozaiCD TEXT,
            ChokyosiCode TEXT,
            ChokyosiRyakusyo TEXT,
            BanusiCode TEXT,
            BanusiName TEXT,
            Fukusyoku TEXT,
            Reserved_229 TEXT,
            Futan REAL,
            FutanBefore REAL,
            Blinker TEXT,
            Reserved_296 TEXT,
            KisyuCode TEXT,
            KisyuCodeBefore TEXT,
            KisyuRyakusyo TEXT,
            KisyuRyakusyoBefore TEXT,
            MinaraiCD TEXT,
            MinaraiCDBefore TEXT,
            BaTaijyu REAL,
            ZogenFugo TEXT,
            ZogenSa REAL,
            IJyoCD TEXT,
            NyusenJyuni INTEGER,
            KakuteiJyuni INTEGER,
            DochakuKubun TEXT,
            DochakuTosu INTEGER,
            Time REAL,
            ChakusaCD TEXT,
            ChakusaCDP TEXT,
            ChakusaCDPP TEXT,
            Jyuni1c INTEGER,
            Jyuni2c INTEGER,
            Jyuni3c INTEGER,
            Jyuni4c INTEGER,
            Odds REAL,
            Ninki INTEGER,
            Honsyokin REAL,
            Fukasyokin REAL,
            Reserved_382 TEXT,
            Reserved_385 TEXT,
            HaronTimeL4 REAL,
            HaronTimeL3 REAL,
            KettoNum1 TEXT,
            Bamei1 TEXT,
            TimeDiff REAL,
            RecordUpKubun TEXT,
            DMKubun TEXT,
            DMTime REAL,
            DMGosaP REAL,
            DMGosaM REAL,
            DMJyuni INTEGER,
            KyakusituKubun TEXT,
            Reserved_462 TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_TC": """
        CREATE TABLE IF NOT EXISTS RT_TC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            HappyoTime TEXT,
            AtoJi TEXT,
            AtoFun TEXT,
            MaeJi TEXT,
            MaeFun TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    # RT_RC: 騎手変更情報 (0B41) - リアルタイム用
    # NL_RCはレコード情報だが、JVRTOpenの0B41は騎手変更情報として別フォーマット
    "RT_RC": """
        CREATE TABLE IF NOT EXISTS RT_RC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            Umaban TEXT,
            KisyuCode TEXT,
            KisyuName TEXT,
            MaeKisyuCode TEXT,
            MaeKisyuName TEXT,
            HenkouJiyuCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_TM": """
        CREATE TABLE IF NOT EXISTS RT_TM (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            MakeHM TEXT,
            Umaban INTEGER,
            TMScore INTEGER,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_WE": """
        CREATE TABLE IF NOT EXISTS RT_WE (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            HappyoTime TEXT,
            HenkoID TEXT,
            TenkoState TEXT,
            SibaBabaState TEXT,
            DirtBabaState TEXT,
            TenkoState2 TEXT,
            SibaBabaState2 TEXT,
            DirtBabaState2 TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HenkoID)
        )
    """,
    "RT_WH": """
        CREATE TABLE IF NOT EXISTS RT_WH (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year TEXT,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            HappyoTime TEXT,
            HenkoID TEXT,
            AtoTenkoCD TEXT,
            AtoSibaBabaCD TEXT,
            AtoDirtBabaCD TEXT,
            MaeTenkoCD TEXT,
            MaeSibaBabaCD TEXT,
            MaeDirtBabaCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HappyoTime, HenkoID)
        )
    """,
    # ========================================
    # 時系列オッズテーブル (TS_O1-O6)
    # オッズの推移を記録するための専用テーブル
    # HassoTimeをPRIMARY KEYに含めて複数時点のデータを保持
    # ========================================
    "TS_O1": """
        CREATE TABLE IF NOT EXISTS TS_O1 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            TanFlag TEXT,
            FukuFlag TEXT,
            WakurenFlag TEXT,
            FukuChakubaraiKey TEXT,
            Umaban INTEGER,
            TanOdds REAL,
            TanNinki INTEGER,
            FukuUmaban INTEGER,
            FukuOddsLow REAL,
            FukuOddsHigh REAL,
            FukuNinki INTEGER,
            Kumi TEXT,
            WakurenOdds REAL,
            WakurenNinki INTEGER,
            TanVote BIGINT,
            FukuVote BIGINT,
            WakurenVote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban, HassoTime)
        )
    """,
    "TS_O2": """
        CREATE TABLE IF NOT EXISTS TS_O2 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmarenFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi, HassoTime)
        )
    """,
    "TS_O3": """
        CREATE TABLE IF NOT EXISTS TS_O3 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            WideFlag TEXT,
            Kumi TEXT,
            OddsLow REAL,
            OddsHigh REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi, HassoTime)
        )
    """,
    "TS_O4": """
        CREATE TABLE IF NOT EXISTS TS_O4 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmatanFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi, HassoTime)
        )
    """,
    "TS_O5": """
        CREATE TABLE IF NOT EXISTS TS_O5 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrenpukuFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi, HassoTime)
        )
    """,
    "TS_O6": """
        CREATE TABLE IF NOT EXISTS TS_O6 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay TEXT,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrentanFlag TEXT,
            Kumi TEXT,
            Odds REAL,
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi, HassoTime)
        )
    """
}


class SchemaManager:
    """Schema management for JLTSQL database.

    Manages table creation and schema operations.
    """

    def __init__(self, db: BaseDatabase):
        """Initialize schema manager.

        Args:
            db: Database instance
        """
        self.db = db

    def get_table_names(self) -> List[str]:
        """Get list of all table names in schema.

        Returns:
            List of table names
        """
        return list(SCHEMAS.keys())

    def create_table(self, table_name: str) -> bool:
        """Create single table.

        Args:
            table_name: Name of table to create

        Returns:
            True if successful, False otherwise
        """
        if table_name not in SCHEMAS:
            logger.error(f"Unknown table: {table_name}")
            return False

        try:
            schema_sql = SCHEMAS[table_name]
            self.db.execute(schema_sql)
            logger.info(f"Created table: {table_name}")
            return True
        except Exception as e:
            logger.error(f"Failed to create table {table_name}: {e}")
            return False

    def create_all_tables(self) -> Dict[str, bool]:
        """Create all tables defined in SCHEMAS.

        Returns:
            Dictionary mapping table names to success status
        """
        logger.info("Creating all tables...")
        results = {}

        for table_name, schema_sql in SCHEMAS.items():
            try:
                self.db.execute(schema_sql)
                logger.debug(f"Created table: {table_name}")
                results[table_name] = True
            except Exception as e:
                logger.error(f"Failed to create table {table_name}: {e}")
                results[table_name] = False

        success_count = sum(1 for v in results.values() if v)
        logger.info(f"Successfully created {success_count}/{len(SCHEMAS)} tables")
        return results

    def table_exists(self, table_name: str) -> bool:
        """Check if table exists in database.

        Args:
            table_name: Name of table to check

        Returns:
            True if table exists, False otherwise
        """
        return self.db.table_exists(table_name)

    def get_existing_tables(self) -> List[str]:
        """Get list of existing tables.

        Returns:
            List of table names that exist in database
        """
        existing = []
        for table_name in SCHEMAS.keys():
            if self.db.table_exists(table_name):
                existing.append(table_name)
        return existing

    def get_missing_tables(self) -> List[str]:
        """Get list of missing tables.

        Returns:
            List of table names that don't exist in database
        """
        missing = []
        for table_name in SCHEMAS.keys():
            if not self.db.table_exists(table_name):
                missing.append(table_name)
        return missing

    def apply_metadata_to_table(self, table_name: str) -> bool:
        """Apply metadata to a specific table.

        Args:
            table_name: Name of table to apply metadata to

        Returns:
            True if successful, False otherwise
        """
        from src.database.schema_metadata import TABLE_METADATA

        # Check if table exists in database
        if not self.db.table_exists(table_name):
            logger.warning(f"Table {table_name} does not exist")
            return False

        # Check if metadata is defined for this table
        if table_name not in TABLE_METADATA:
            logger.warning(f"No metadata defined for table {table_name}")
            return False

        metadata = TABLE_METADATA[table_name]
        db_type = self.db.get_db_type()

        try:
            if db_type == "sqlite":
                # SQLite: Use _metadata table
                # Create _metadata table if it doesn't exist
                self.db.execute("""
                    CREATE TABLE IF NOT EXISTS _metadata (
                        table_name TEXT NOT NULL,
                        column_name TEXT NOT NULL DEFAULT '',
                        description TEXT,
                        metadata_type TEXT NOT NULL DEFAULT 'column',
                        PRIMARY KEY (table_name, column_name)
                    )
                """)

                # Insert table description (column_name is empty string for table descriptions)
                self.db.execute(
                    """INSERT OR REPLACE INTO _metadata (table_name, column_name, description, metadata_type)
                       VALUES (?, '', ?, 'table')""",
                    (table_name, metadata.get("description", ""))
                )

                # Insert column descriptions
                for col in metadata.get("columns", []):
                    col_name = col.get("name", "")
                    col_desc = col.get("description", "")
                    if col_name:
                        self.db.execute(
                            """INSERT OR REPLACE INTO _metadata (table_name, column_name, description, metadata_type)
                               VALUES (?, ?, ?, 'column')""",
                            (table_name, col_name, col_desc)
                        )

            elif db_type in ("postgresql", "duckdb"):
                # PostgreSQL/DuckDB: Use COMMENT ON
                # Table comment
                table_desc = metadata.get("description", "").replace("'", "''")
                self.db.execute(f"COMMENT ON TABLE {table_name} IS '{table_desc}'")

                # Column comments
                for col in metadata.get("columns", []):
                    col_name = col.get("name", "")
                    col_desc = col.get("description", "").replace("'", "''")
                    if col_name:
                        # Use double quotes for column names with Japanese characters
                        self.db.execute(f'COMMENT ON COLUMN {table_name}."{col_name}" IS \'{col_desc}\'')

            logger.info(f"Applied metadata to table {table_name}")
            return True

        except Exception as e:
            logger.error(f"Failed to apply metadata to {table_name}: {e}")
            return False

    def get_table_metadata(self, table_name: str) -> dict:
        """Get metadata for a specific table.

        Args:
            table_name: Name of table

        Returns:
            Dictionary with table and column metadata
        """
        db_type = self.db.get_db_type()
        result = {"table": None, "columns": {}}

        try:
            if db_type == "sqlite":
                # Query _metadata table
                if not self.db.table_exists("_metadata"):
                    return result

                # Get table description (column_name is empty string)
                rows = self.db.fetch_all(
                    "SELECT description FROM _metadata WHERE table_name = ? AND column_name = ''",
                    (table_name,)
                )
                if rows:
                    result["table"] = rows[0]["description"]

                # Get column descriptions
                rows = self.db.fetch_all(
                    "SELECT column_name, description FROM _metadata WHERE table_name = ? AND column_name != ''",
                    (table_name,)
                )
                for row in rows:
                    result["columns"][row["column_name"]] = row["description"]

            elif db_type in ("postgresql", "duckdb"):
                # Query information_schema or pg_description
                # Implementation depends on specific database
                # For now, return empty (can be enhanced later)
                pass

        except Exception as e:
            logger.error(f"Failed to get metadata for {table_name}: {e}")

        return result

    def apply_all_metadata(self) -> Dict[str, bool]:
        """Apply metadata to all tables that have metadata defined.

        Returns:
            Dictionary mapping table names to success status
        """
        from src.database.schema_metadata import TABLE_METADATA

        results = {}
        for table_name in TABLE_METADATA.keys():
            results[table_name] = self.apply_metadata_to_table(table_name)

        success_count = sum(1 for v in results.values() if v)
        logger.info(f"Applied metadata to {success_count}/{len(results)} tables")
        return results


def create_all_tables(db: BaseDatabase) -> None:
    """Create all tables defined in SCHEMAS.

    Args:
        db: Database instance
    """
    logger.info("Creating tables...")
    for table_name, schema_sql in SCHEMAS.items():
        try:
            db.execute(schema_sql)
            logger.debug(f"Created table: {table_name}")
        except Exception as e:
            logger.error(f"Failed to create table {table_name}: {e}")
            raise
    logger.info(f"Successfully created {len(SCHEMAS)} tables")